### ISSUE TITLE
[Feature Request] Background Playback Activation with ONLY Back Button

### ISSUE THREAD

**Issue by bkmcleod90** [yuliskov/SmartTube#1340]
Currently using STN Beta with my CCwGTV. Background playback options are limited to HOME and BACK/HOME options.

A back button only activation would allow browsing the STN app with background play but cut off playback when home is selected. 

Furthermore, under settings for exiting the app it would allow the back button to continue playback on the home screen if desired. This functionality would remove the need to always pause a video before leaving the app.

EDITS: for clarity, spelling, formatting.

**Comment by bkmcleod90** [comment]
UPDATE:

If anyone is looking for similar functionality from STN as described above. Enabling "Don't Keep Activities" within your Android TVs Developer Options will get this working with the HOME/BACK activation for Background Playback enabled as a stop gap.

Draw backs are that you will need to relaunch all apps installed on your system not just STN immediately after pressing home or launching a different app via hotkeys. 

Still testing this but it seems to be an issue when manually toggling a screensaver app, for example.

Obviously, a better solution would be to have STN manage itself in this manner so a blanket developer option is not required. Cheers!

**Comment by Loading617** [comment]
And pip too

**Comment by MD77MD** [comment]
ability to choose what action trigger what playback mode

ex. 
back button ==> PiP
home button ==> background mode
