### ISSUE TITLE
All videos not shown while browsing channel. 

### ISSUE THREAD

**Issue by LeCommonMan** [yuliskov/SmartTube#1344]
new bug:
While browsing a channel, all videos are not listed,
only "past live stream" video will be available.

Exit, app, clear cache is the workaround i figured out yet. which is again working for only 1-2 channels. 

Note: this was earlier once in a while bug but in recent week or so its very prominent, that i have t resort back to official yt app.

**Comment by kupony** [comment]
I'll add to this issue. Often times I call "open channel" using context menu - and the channel page will not show recent uploads or videos. Just like LeCommonMan above describes - often it only lists past live streams. It used to work just fine until about 3-4 weeks ago. It's not happening on every channel - but it does happen more often recently.

**Comment by costinmx** [comment]
I also confirm the issue, seen in the past month, as described above.

**Comment by keldian** [comment]
Having this issue with the NBA channel. Only showing past live streams.

**Comment by LeCommonMan** [comment]
this issue returned back in version 18.15 and can be observed intermittently. where "uploads" section of a channel are often missing. 

restarting app sometime fix issue.

**Comment by LeCommonMan** [comment]
old issue, closing
