### ISSUE TITLE
Version 15.81 won't install 

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#1798]
Every version has a buffering issue, I have tried every previous version upto 14.16 and they all buffer massively, I wanted to try the updated version 15.81 due to reading success to fixing the buffering, Yet it won't install.

**Comment by ACR-Jeff** [comment]
Well after posting this I found a solution, I am still unable to install 15.85 Yet I was able to install 15.62 and it fixed the buffering issues. If you're having buffering issues and unable to install 15.85 try 15.62.

**Comment by ACR-Jeff** [comment]
Ok I spoke too soon, Now having major buffering issues on 15.62, What is the issue with 15.81 not installing?

**Comment by JF5ebastian** [comment]
Same problem here. I'm unable to install 15.81 on Nvidia Shield Tv Pro 2019 model. I tried uninstalling the current version but it won't install at all now.
