### ISSUE TITLE
The new language ai voice-over doesn't work too well with this

### ISSUE THREAD

**Issue by FN1X** [yuliskov/SmartTube#2112]
so, a bit confusing title I know but in basic terms, youtube added a feature where *NEW* videos get to run through an ai to create a voice-over for other languages. however, your app doesn't have the option to disable or modify this, and this very quickly becomes a problem. 

Example: https://youtube.com/watch?v=uaHmtJrZRdM&t

this video pretty much seems normal on all *official* YT apps, however, if you watch this video on SmartTube. the video seems to be in French. 

Now, this feature only affects some channels, but just in case I just wanted to report this to ya

**Comment by Itsxdfishyyy** [comment]
This may be my issue as well. Strange.
