### ISSUE TITLE
Playback mode ignored; videos keep playing regardless of setting

### ISSUE THREAD

**Issue by y-lee** [yuliskov/SmartTube#2480]
I have Playback mode set to "Pause playback after each video". As of 17.83, the setting is ignored. SmartTubeNext behaves as if "Play videos continuously" is set.

EDIT: "Repeat current video" functions correctly. "Pause playback after each video" (as mentioned) and "Stop playback after one video" do not work.

EDIT 2: "Pause playback after each video" does work when opening a channel then playing a video from there.

**Comment by Riusakii** [comment]
Having exact same issue since updating the latest version (Beta 17.83) last night.

> I have Playback mode set to "Pause playback after each video". As of 17.83, the setting is ignored. SmartTubeNext behaves as if "Play videos continuously" is set.
> 
> EDIT: "Repeat current video" functions correctly. "Pause playback after each video" (as mentioned) and "Stop playback after one video" do not work.

**Comment by Vinny1967** [comment]
Same here.

**Comment by borislip** [comment]
Same here. Please fix.

**Comment by borislip** [comment]
Just installed 17.84, fixed indeed, thanks.
