### ISSUE TITLE
Keeps Crashing Continuously

### ISSUE THREAD

**Issue by 44cK3r** [yuliskov/SmartTube#2550]
It Keeps Crashing On My TV Over And Over And Over Again I'd Put On A Video And Within A Few Minutes The Video Crashes Then Not Long After The App Crashes Or It Just Crashes In One Go I Can't Use It Anymore Can You Please Fix It If You Need More Details Like What Kind Of TV Or Anything Just Let Me Know And I'll Try And Get Back To You Because My Notifications Don't Work Properly And I Have Short Term Memory Loss Either Way Lots Of Love Keep It Up And Stay Positive

**Comment by ypk** [comment]
can you try installing a previous version and see if that's stable for you: https://www.apkmirror.com/apk/yuliskov/stn-stable-android-tv/ ?

**Comment by 44cK3r** [comment]
> can you try installing a previous version and see if that's stable for you: https://www.apkmirror.com/apk/yuliskov/stn-stable-android-tv/ ?

Ok I'll try thank you it's also now saying something like this (video source not working or wrong time) something like that I can't remember the exact words but I'll try the previous version

**Comment by 44cK3r** [comment]
> can you try installing a previous version and see if that's stable for you: https://www.apkmirror.com/apk/yuliskov/stn-stable-android-tv/ ?

So far so good with the previous version thank you
