### ISSUE TITLE
Videos won’t play (19.63) (Nokia Streaming Box 8000)

### ISSUE THREAD

**Issue by claytonfk** [yuliskov/SmartTube#2983]
I have been experiencing the issue of videos not playing over the past 3 days. I am using the latest version of the app.  However, I have also tried downgrading to even older versions such as 19.17. The videos won’t simply play (there is a loading circle in the middle that stays there forever while the rest of the screen is all black). 

Other things I tried: force stop the app, uninstall and reinstall the app, sign out and back in, restarted the Android box, and restarted the WiFi router.

**Comment by Leetjuns** [comment]
Had the same issue, video preset was 4k somehow after update.
Changed it to "without preset" and it works fine again. (for me that is)
In the STN UI -> Settings -> video player -> video presets -> (tick) without preset 

Hope this works for you...

**Comment by claytonfk** [comment]
> Had the same issue, video preset was 4k somehow after update. Changed it to "without preset" and it works fine again. (for me that is) In the STN UI -> Settings -> video player -> video presets -> (tick) without preset
> 
> Hope this works for you...

Unfortunately it still does not work. I tried other presets too. I also tried 19.64 Beta.

**Comment by Haris1977** [comment]
I wanted to buy nokia 8000 ONLY for smarttube app

It still wont play with latest versions?
