### ISSUE TITLE
Request: Add/remove labels in left side panel

### ISSUE THREAD

**Issue by Haris1977** [yuliskov/SmartTube#3017]
A nice feature will be to have the ability to add/remove (customize) labels on the left side panel 

E.g i want to remove the "shorts" or "music" label (look yellow circle in photo below):

https://i.postimg.cc/Pr2WDqVT/IMG-3772.jpg

Can this somehow be implemented?

**Comment by Ed254** [comment]
You can add or remove the panels by going to settings, general, set-up sections and UNTICK whatever you don't want to appear.

**Comment by Haris1977** [comment]
Thank, i didnt notice it

:)
