### ISSUE TITLE
Error, error and many more errors!!!

### ISSUE THREAD

**Issue by tomekwwa** [yuliskov/SmartTube#3049]
For me, the last working version was 18.23 stable. But logging into account is not working any more on 18.23. I've tried most of other newer versions, but there are always errors like: invalid integer size, error null and so on, on every single video. It is impossible that anyone is using it like this. I have Philips Android TV, MiTV on Android, MiBox 4K and another tv box. There are the same errors on every device. Three different internet providers tested. YT Premium is working without any errors. DO SOMETHING PLEASE.

**Comment by tomekwwa** [comment]
![IMG_20231124_191449](https://github.com/yuliskov/SmartTube/assets/80062158/01c787b8-a571-40a2-8bdc-c4604e4539d4)
![IMG_20231124_191429](https://github.com/yuliskov/SmartTube/assets/80062158/f22cd2f9-f590-45be-826a-e602fdd5357d)
![IMG_20231124_191410](https://github.com/yuliskov/SmartTube/assets/80062158/8afeee2b-165c-4ec4-a9a1-314f0623c22f)
![IMG_20231124_191345](https://github.com/yuliskov/SmartTube/assets/80062158/4e0d8066-a4aa-41cb-a19f-8e3629b83fb1)

**Comment by tomekwwa** [comment]
On 20.04 is a little better, no SSL or array errors,  but now it is showing one error all the time Resposnse Code 400.
![IMG_20231125_093631](https://github.com/yuliskov/SmartTube/assets/80062158/ac3e40ca-0587-4d65-9893-f041dde08e69)

**Comment by mmick08** [comment]
+1 same here.

**Comment by crypt0sis2019** [comment]
Go into settings and cha ge network stack from cronet to builtin. Hadd all the same errors and this fixed it for me across all my android tv devices.

**Comment by crypt0sis2019** [comment]
> > Go into settings and change the network stack from cronet to builtin. Had all the same errors and this fixed it for me across all my android tv devices.
> 
> These errors were not related to cronet protocol.

Hmm either way it stopped the errors for me that had been going on for over a month. Using on a 4k Chromecast with Google TV.   I'll update to the 20.19 and see what happens.
