### ISSUE TITLE
Open via command 

### ISSUE THREAD

**Issue by QapaMcFly** [yuliskov/SmartTube#3095]
Hello is there a way to open smarttube and play certain url ? I found something like 
android.intent.action.VIEW but that opens browser on my android tv instead of smarttube. 

Thanks :)

**Comment by yomgui** [comment]
The following command demonstrates how to use the Android Debug Bridge (ADB) to launch a specific application with an intent

```
adb shell am start -a android.intent.action.VIEW -d "https://www.youtube.com/watch?v=DYpNU_3oPYk" com.liskovsoft.smarttubetv.beta
```

**Comment by QapaMcFly** [comment]
Works ill just add to use com.teamsmart.videomanager.tv if not using beta release
