### ISSUE TITLE
[BUG] Sidebar Playlist 15 Videos Limit

### ISSUE THREAD

**Issue by github-monkey** [yuliskov/SmartTube#3286]
This has been an issue going back several months, even with the latest versions (20.90 at the time of writing):

When I pin a playlist which has more than 15 items to the sidebar, after a day or so only the first 15 items in the playlist are visible. To restore all items, the playlist has to be removed from the sidebar and pinned again.

**Comment by github-monkey** [comment]
Correction: This does seem to (eventually) effect any playlist with over 15 items.

**Comment by xsuper9988** [comment]
> This seems to (eventually) effect many playlists with over 15 items, but not all.
> 
> For example, this playlist is effected:
> 
> https://youtube.com/playlist?list=PLN39y5i_H0FmkTDiz7ijCf_8inmuZbeYc&si=az36KHdypJlci84O
> 
> After removing the playlist from the sidebar and adding it again, it will show all items for a short while, but within a day or two it will only show item 1 to 15. If you remove it again from the sidebar and add it again, the same thing will happen.
> 
> Other playlists with more than 15 items don't seem to be effected at all, and will show all their items without ever any issues. For example, this one: https://youtube.com/playlist?list=PLWKuyAKXafnJPKgIaXKko9XBchLqfA0iN&si=9ub6KuxllxxMiRVE

Excuse me
Does "notification" have the same problem with only 20 videos?
If it's not the same problem, can "notification" display more videos?
How to set it?
Thank you very much for your help and replies

**Comment by N3orun** [comment]
Having the same issue since multiple versions. Extremely annoying, especially for the watch later playlist. 

Would love to see this solved!

**Comment by godzilla360** [comment]
My guess is that there is code to limit loading the number of videos to 15 when the Playlist display mode is set to ROWS.

This is probably to prevent the UI from having to scrolling through 15+ videos horizontally.

However, when Playlist display mode is set to GRID, there should be no limit and it's probably supposed to work that way, but there's a bug that may cause it to happen.

**Comment by godzilla360** [comment]
> Other playlists with more than 15 items don't seem to be effected at all, and will show all their items without ever any issues. For example, this one:
> https://youtube.com/playlist?list=PLWKuyAKXafnJPKgIaXKko9XBchLqfA0iN&si=9ub6KuxllxxMiRVE

I just tested this list.  It cuts off at 15 videos.

**Comment by github-monkey** [comment]
Yes, it seems to be inconsistent. Some playlists pinned to the sidebar cut
off items over 15 quite quickly, others after a while and some just keep
showing all items.

**Comment by github-monkey** [comment]
@godzilla360 It seems to be solved from at least 22.81. Is that your experience as well?
