### ISSUE TITLE
Fix interface for Quest (3)

### ISSUE THREAD

**Issue by entchen66** [yuliskov/SmartTube#3323]
Hey, I am now on the last version and was wondering if it would be possible to change the ration of the whole app for the Quest to 16:9, like on AndroidTV.

![WhatsApp Bild 2024-03-08 um 14 06 01_88a324b5](https://github.com/yuliskov/SmartTube/assets/1564726/aa4e4536-036e-4f2f-a715-90b452d64a73)
![WhatsApp Bild 2024-03-08 um 14 02 50_91ff9eda](https://github.com/yuliskov/SmartTube/assets/1564726/4f8bdda4-7282-4821-9c28-e4b54bac4ff4)

It works quite well on TV. So I hope it is possible to also fix it on the Quest, so it could be used as a great YouTube app :)

I am here to give feeback and help. If needed some debugging and testing, just head out to me.

Greetings Chris

**Comment by inertia666** [comment]
There is an "oculus" fix in the developer mode setting. It  makes everything work properly with the menus. The only thing I dont seem to be able to do is use my Google account to login (it works on the TV).
