### ISSUE TITLE
Unknown error. Unable to connect!

### ISSUE THREAD

**Issue by MomenMamdouh** [yuliskov/SmartTube#3337]
SmartTube fails to play some videos and the number increases day after day. Here is the error message that I get.

![IMG20240312123721](https://github.com/yuliskov/SmartTube/assets/19880069/d99df5b2-50ee-4603-83c1-365f5ef76a5a)

Official YouTube, and Revanced app don't face this error.

Tried different versions including the latest stable and beta ones but to no avail 😕

And here are some links to some videos that make the error appears:

https://youtu.be/8WHSfxyE4Uc
https://youtu.be/fOYmHPmvSVg
https://youtu.be/TQxwqY-m30Y

**Comment by MomenMamdouh** [comment]
It's an error on the router level. Not SmartTube fault.

But i'm surprised that official YouTube and Revanced apps are not affected.

Anyway consider it closed.

**Comment by eamvdivwjc193** [comment]
@MomenMamdouh I'm haivng the same issue. Would you please share how to get this fixed in your router? My observation is that if I'm using the official app on my phone, there was just one connection to the video source, while SmartTube will have up to 20+ connections, which is quite strage. And SmartTube stopped working, myabe when it exceeds the connection limit, just guess.

**Comment by lubianyehou** [comment]
> It's an error on the router level. Not SmartTube fault.
> 
> But i'm surprised that official YouTube and Revanced apps are not affected.
> 
> Anyway consider it closed.

 I'm haivng the same issue. Would you please share how to get this fixed in your router?

**Comment by lubianyehou** [comment]
> @MomenMamdouh I'm haivng the same issue. Would you please share how to get this fixed in your router? My observation is that if I'm using the official app on my phone, there was just one connection to the video source, while SmartTube will have up to 20+ connections, which is quite strage. And SmartTube stopped working, myabe when it exceeds the connection limit, just guess.

maybe you can chance the client.
I chance this client,Its no problem.
You can have a try.
https://[mega.nz/folder/Q5ww0KYA#j71EKkvsdCir7f4QvJPKhA](https://mega.nz/folder/Q5ww0KYA#j71EKkvsdCir7f4QvJPKhA)
