### ISSUE TITLE
Can't see replies to comments anymore

### ISSUE THREAD

**Issue by flitzekex** [yuliskov/SmartTube#3389]
For some reason, after the latest update, the app doesn't show replies to comments anymore. 
Every comment just looks like a comment without replies, even though they do have replies in the app or on the website.

**Comment by twiikker** [comment]
Same issue with version 21.54 on nvidia shield tv pro 2017.

**Comment by sujal-0611** [comment]
Same issue , anyone knows when it gonna be fixed?

**Comment by flitzekex** [comment]
Seems to be fixed in the beta version so I guess it will be fixed in the stable release very soon.

**Comment by flitzekex** [comment]
Fixed with update 21.69
