### ISSUE TITLE
Video only works when casting from phone

### ISSUE THREAD

**Issue by ulanas** [yuliskov/SmartTube#3395]
Hello. First of all - this is hands down, the best youtube app for the TV. Thank you for that.

Yesterday, an issue has started, where whichever video I select using remote, is not being played. Instead of it, I get this error (last one appeared today): 
![IMG_2247](https://github.com/yuliskov/SmartTube/assets/106864015/4fbf1df9-ce02-4e25-aee0-08509db43ee6)
![IMG_2246](https://github.com/yuliskov/SmartTube/assets/106864015/60335f32-0ef0-4adb-a305-79c19203dd53)
![IMG_2248](https://github.com/yuliskov/SmartTube/assets/106864015/01616c7d-6871-4c7e-968b-5ef82f4cd838)

However, if I try to cast from phone, the video is played through TV without issues. After that, I can select the same video through the menu on the TV, and it will work as normal, but only that video, and not the others.

Thanks.

**Comment by DangerDaaku** [comment]
The obligatory thanks to the builder for this app for making perhaps a single most greatest app for humanity.

My issues #3390  is quite similar.

I cannot even cast from my phone.

When playing videos I get errors like these

![20240330_222011](https://github.com/yuliskov/SmartTube/assets/165342545/cce53a44-517a-4b78-893e-3e453fec13bf)
![20240329_132658](https://github.com/yuliskov/SmartTube/assets/165342545/0ffe2a0f-a688-4ca0-ae40-7a3934575303)

**Comment by ulanas** [comment]
Yup, it looks similar. The one thing I've tested today, is that if I use hotspot from my phone for the TV, the video plays, when I switch back to the home wifi, it's not working again.

**Comment by ulanas** [comment]
Tried with mohile hotspot and it worked, so left my modem disconnected for 30mins to reset ip, and now it works flawlessly!

**Comment by ulanas** [comment]
Other solutions offered through telegram channel: Network errors can happen because of
- actual network issues, check your connection
- sometimes (for unknown reasons) it helps to go to settings/player/network stack and change the selection
- connection being blocked by an ad-blocking app or DNS or /etc/hosts (usually you'd know about it, if you're using these)
- YouTube servers are blocking your IP (try rebooting your router or enabling/disabling/switching VPN)
- YouTube changed their unofficial API (SmartTube needs to update) Network errors can happen because of
- actual network issues, check your connection
- sometimes (for unknown reasons) it helps to go to settings/player/network stack and change the selection
- connection being blocked by an ad-blocking app or DNS or /etc/hosts (usually you'd know about it, if you're using these)
- YouTube servers are blocking your IP (try rebooting your router or enabling/disabling/switching VPN)
- YouTube changed their unofficial API (SmartTube needs to update)
