### ISSUE TITLE
Add brightness modificator (for dimming screen)

### ISSUE THREAD

**Issue by joacopaz** [yuliskov/SmartTube#3399]
Hi @yuliskov ! Thanks for this application, it's absolutely amazing and has been a game changer for me and my wife. We use it every day and am impressed but the amazing support it receives and the day to day improvements you add. I read every single update to see what's new.

I wanted to request a brightness modificator, an action to dim the screen (say from 100% to 30%). Just adding a dimmable black box on top of the videos that inversely relates to the value of the % (100% = `opacity 0`, 20% = `opacity 0.8`) to make the screen darker.

The reason I would love this is because when we watch smart tube at night, sometimes we're getting sleepy and fire tv does not allow us to change the brightness of the screen and some videos are too bright, which are a nuisance when watching at night and a little too contrasting for my taste. I'm currently using the tv remote to dim the brightness natively, but would love if smart tube had it's own brightness state we could manage to get this same effect directly inside the app.

I would add it myself, and have been looking into the repo, but my android/java skills are subpar, I'm mostly a web/js developer and find it a little tough to navigate the repo. If you'd give me a nudge in the right directions I would try adding it myself.

Thanks, again, for this amazing application!

**Comment by yuliskov** [comment]
Open player, then press on the 'screen off' button. You should be able to
select dim amount from there.

Regards, Yuriy

**Comment by joacopaz** [comment]
I tested this but on the screen off button inside `Settings -> Video Interface` I can just select the ammount of time for the screen to timeout and turn off (turn off completely, pitch black). I can choose dim % in the `Settings -> General` (but these only apply to the general application, not the Video Player). Am I missing something?

**Comment by yuliskov** [comment]
@joacopaz Enable this player button: Settings/Player/Buttons/Screen off
Then, inside the player, you can control the dimming (long press for menu, short for toggle).

**Comment by joacopaz** [comment]
Thanks! It was the long press that allowed me to configure it inside the player, I didn't know video player options had dynamic behaviors like that, neat!

Thanks a lot for the quick replies
