### ISSUE TITLE
Music Section is no longer showing Liked Music/Songs Playlist

### ISSUE THREAD

**Issue by Crissley10** [yuliskov/SmartTube#3495]
Recently like ever since a few days ago, the Music section is not showing the Liked Music/Songs playlist anymore. However, I don't think the issue is related to the new SmartTube updates though because one of my other devices has an older version of SmartTube (I had last updated that one like 2 or 3 weeks ago) so I decided to check out if the playlist in the Music section was still available, but despite having been the version from a couple of weeks ago, it also was not displaying that Liked Music playlist either. I really hope this can be easily fixed.

**Comment by Crissley10** [comment]
YEY it's been fixed!

**Comment by Itsjustahobby** [comment]
What version do you have for your SmartTube for this to be working? Cause I have Version 21.91 which I assume is the latest but I still don't see the "liked music/song" playlist.

**Comment by Crissley10** [comment]
> What version do you have for your SmartTube for this to be working? Cause I have Version 21.91 which I assume is the latest but I still don't see the "liked music/song" playlist.

**Comment by Crissley10** [comment]
> > What version do you have for your SmartTube for this to be working? Cause I have Version 21.91 which I assume is the latest but I still don't see the "liked music/song" playlist.

I'm using the latest current build (21.92) but that doesn't matter. Turns out, the playlist is gone again. Luckily, I did add the playlist to my sidebar in case this issue resurfaced. Having it on the side bar does allow me to view and use the playlist as you normally would through the Music section. But yeah, for some reason it is yet again not available in the Music section anymore. Hopefully this gets fixed again permanently for anyone who hasn't preemptively added the playlist to their side bar while it was available. Here's teo screenshots, one showing where it is supposed to be, and the other showing that it's functioning still if added the sidebar preemptively.
![Screenshot_20240527_122144_SmartTube beta](https://github.com/yuliskov/SmartTube/assets/80502975/b77a6337-ef96-4ce7-8bdf-51769e9b7268)
![Screenshot_20240527_122358_SmartTube beta](https://github.com/yuliskov/SmartTube/assets/80502975/1e1dd46a-506d-4d85-a1e8-72723a4b319f)

**Comment by Crissley10** [comment]
The playlist is fixed again as of version 22.06! ![mutsukicaliphornia](https://github.com/yuliskov/SmartTube/assets/80502975/ce6d70f3-72b0-4318-8625-61f35dc1a15e)
![Screenshot_20240617_184643_SmartTube beta](https://github.com/yuliskov/SmartTube/assets/80502975/f022a6bd-5bd7-4b7c-90a1-0c426702dbdf)
![Screenshot_20240617_184920_SmartTube beta](https://github.com/yuliskov/SmartTube/assets/80502975/a66a8b13-010b-42a9-bd4f-307cdee367b2)

**Comment by harveb** [comment]
Hi,

This issue appears to have occurred again

**Comment by Crissley10** [comment]
> Hi,
> 
> This issue appears to have occurred again

This seems to be functioning fine for me, the only thing of note this time around is that the "Liked Music" section is now just named "Music". It's still at the top of the music tab. Different name, but still has the same functionality.
![Image](https://github.com/user-attachments/assets/37a4694e-ac8e-4b21-bd8f-12343fac8626)

**Comment by harveb** [comment]
Yeah but now I can't pin that list to my sidebar or find the "Liked Music" playlist item. I don't have access to the menu for that playlist. Can't save it.

Also why was it changed? Seems like a random thing to change when it was functioning perfectly.

**Comment by Crissley10** [comment]
> Yeah but now I can't pin that list to my sidebar or find the "Liked Music" playlist item. I don't have access to the menu for that playlist. Can't save it.
> 
> Also why was it changed? Seems like a random thing to change when it was functioning perfectly.

Don't know why they renamed it, but it doesn't really matter in the end. Anyways, I don't see why you don't have the option to add the playlist to your sidebar, it displays the options just fine for me as you can see here in my screenshot. To open this menu, all you have to do is press and hold on any song in that list, really doesn't matter which one, and then scroll down and the options to add the playlist to your sidebar should be one of the available options.
![Image](https://github.com/user-attachments/assets/2349db2a-0dae-4b26-a89b-b27362a82c7d)

**Comment by harveb** [comment]
Ahh okay thanks that does what I need. Still weird that features are renamed without any notes or heads up. Makes me worried about what else changes without being noted.

Thanks
