### ISSUE TITLE
no audio on certain parts of youtube videos 

### ISSUE THREAD

**Issue by AlexWolfz** [yuliskov/SmartTube#3508]
When watching a video like the choicer voicer from vinesauce, when the audio for certain parts that doesn't have vinny himself say it plays, it's completely mute for seemingly no discernable reason. This is not a issue with mobile, pc or even the official youtube app. So I'm quite unsure what could be causing this.

**Comment by AlexWolfz** [comment]
Seems to be for music and sfx in game

**Comment by AlexWolfz** [comment]
Seems to be a issue with sfx and music in games too when watching them

**Comment by mcswizzle** [comment]
I'm also experiencing this with a Walmart Onn 4K (Non-Pro) using SmartTube and/or beta. It seems to occur on longer videos (20+ mins) most in my experience. Audio cuts out irregularly for an indeterminate amount of seconds before sounds returns.

**Comment by AlexWolfz** [comment]
Turns out it was setting itself on (descriptive) when it came to audio format. 
Switching it to original solved all my issues.

**Comment by mcswizzle** [comment]
Turns out mine was related to a cable setup. Moving to Bluetooth works perfectly, apologies for the mis-report.
