### ISSUE TITLE
YouTube button on Google TV not opening Smarttube

### ISSUE THREAD

**Issue by dorianps** [yuliskov/SmartTube#3512]
I have three Google TV at home. For some reason, the YouTube button works great to open SmartTube on two of them, but the most recent one I installed few days ago opens the YouTube installation option. Note that I have uninstalled the YouTube app from all of them. Can't find what did I do different before, and no info online either. 

Any help?

**Comment by SMNFXCN** [comment]
There are button remapper tools on the Play Store, try to see if you can map a button to open an app.

**Comment by dorianps** [comment]
Found the solution. Myistake for having missed the following steps from the installation. Works like a charm now.


On Google Chromecast with Google TV:

uninstall the original YouTube app (no root required)
download and install the ATV Bridge SmartTube app: https://kutt.it/stn_bridge_atv (e.g. via Downloader by AFTVnews)

**Comment by aab44** [comment]
Same issue

Any solution to install ATV Bridge SmartTube apk (ATV_SYTV_Bridge.apk)


> > Found the solution. My mistake was missing the following steps from the installation. Works like a charm now.
> > On Google Chromecast with Google TV:
> > uninstall the original YouTube app (no root required) download and install the ATV Bridge SmartTube app: https://kutt.it/stn_bridge_atv (e.g. via Downloader by AFTVnews)
> 
> Doesn't work on my Sony Google TV X80K. Installing ATV_SYTV_Bridge.apk still said "failed to install".
> 
> Can't uninstall the original YouTube app from the TV; can only uninstall the update.
> 
> Then, I tried to uninstall all Youtube app with both method (show 0KB):
> 
> * with ADB TV: App Manager from Google Play Store
> * all the steps from this [Reddit Comment](https://www.reddit.com/r/AndroidTV/comments/1dcbqlq/comment/l85u67r/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) with ADB TV: App Manager Console
> 
> I used [apk-editor-studio](https://github.com/kefir500/apk-editor-studio) to change the Bridge apk to a high version (tried 5 or 20 or 100).
> 
> Also tried with Youtube app installed and only uninstall the updated version.
> 
> Major problem I think is that Sony TV consider the Youtube app as system app. It shows in the system app even after uninstall (0KB) with either method. It couldn't replace the system app.
> 
> Let me know if anyone has a fix. Much appreciated!
