### ISSUE TITLE
Subtitles are automatically on

### ISSUE THREAD

**Issue by Hexinator1302** [yuliskov/SmartTube#3580]
Hi, since today's update to version beta 22.11, subtitles are enabled for every video. A long press on CC takes me to the options. Here the subtitles are always enabled. I then disable the subtitles and they are gone. 

However, when I quit and restart the video, the subtitles are back on. As mentioned above, this happens with all videos.

**Comment by Zebrahead100** [comment]
Same here.

**Comment by Zebrahead100** [comment]
Obviously solved with latest update 22.12 - thank you!

**Comment by Hexinator1302** [comment]
I can confirm this. Thanks for the update.
