### ISSUE TITLE
Overlay permission (FireTV 4k 2nd Gen)

### ISSUE THREAD

**Issue by TaiyakiFox** [yuliskov/SmartTube#3593]
Everytime I start the App I get the Message "Background remote control requires overlay permission" (translated from german).

FireTV 4k 2nd Gen

Any ideas?

**Comment by unwishedjack** [comment]
> Everytime I start the App I get the Message "Background remote control requires overlay permission" (translated from german).
> 
> FireTV 4k 2nd Gen
> 
> Any ideas?

I get this also, I'm on 22.19 Stable

**Comment by TaiyakiFox** [comment]
Remote controll means you can play videos from the mobile YouTube app on smarttube with one (or two) klicks. I didn't know this option is called like that - it can be turned off in the settings.
