### ISSUE TITLE
SmartTube 22.37 on FireStick.

### ISSUE THREAD

**Issue by Chris-Treleaven** [yuliskov/SmartTube#3625]
Updated the app, now videos won't play. Just saying 'Unknown source error. Response code 403'

**Comment by HansRandomizer** [comment]
Same here

**Comment by Dongjin104** [comment]
I'm experiencing the same issue.
It doesn't seem to be an update problem.
The same issue occurred even with the previous version. Hopefully, developers will notice and fix it soon.

**Comment by ACR-Jeff** [comment]
Duplicate https://github.com/yuliskov/SmartTube/issues/3606
