### ISSUE TITLE
Error 403 (again)

### ISSUE THREAD

**Issue by diegoX-X** [yuliskov/SmartTube#3637]
Error 403 persists after the last 2 updates, would be nice to be informed if this is on youtubes side or what. Second update worked for about a day, then errors again.

**Comment by poggersv2** [comment]
I have the same issue, last night, I updated to the 403 fix, but today it stopped working again

**Comment by diegoX-X** [comment]
Installed 22.37. No change. I do thank the dev on the frequent updates and attempted bugfixes and would like to make clear that my frustration is directed squarely towars youtube.

**Comment by diegoX-X** [comment]
22.39 is the one that solved it! Thanks to the dev!
