### ISSUE TITLE
403 errors since yesterday 

### ISSUE THREAD

**Issue by tonydiep** [yuliskov/SmartTube#3638]
Experiencing 403 errors on Chromecast with Google TV with 22.35 and whatever is current on 2024-07-09

**Comment by tonydiep** [comment]
403 error on versions 22.36, 22.35, and 22.33 on Chromecast with Google TV

**Comment by IntNinja** [comment]
> 403 error on versions 22.36, 22.35, and 22.33 on Chromecast with Google TV

Duplicate of #3606

**Comment by IntNinja** [comment]
it's a known issue

**Comment by jackL999** [comment]
Same. It just started with the latest beta update.

**Comment by ACR-Jeff** [comment]
Would people please start doing a search before posting, There are already 50-100 posts about this issue.

**Comment by lucpet** [comment]
I only just updated again today after updating yesterday and the same issue is still there.

**Comment by ilex2023** [comment]
I also encountered a 403 error on version 22.xx, which made it impossible to use it normally. I am going to roll back to 21.xx to see if there will be similar problems.

**Comment by tonydiep** [comment]
Closing. Duplicate.

**Comment by Anonymous941** [comment]
Thank you

**Comment by IntNinja** [comment]
Also 22.38 is fixing it for lot of devices, try installing it and see
