### ISSUE TITLE
Question - How are issues related to YouTube restrictions solved?

### ISSUE THREAD

**Issue by Sarafian** [yuliskov/SmartTube#3654]
Hi,
I'm not an Android App developer, so forgive my potential lack of knowledge of the obvious.

Given the recent crackdown from YouTube and therefore outage of the app, I thought to check how you guys address the issue.

So, I checked the last releases for differences in the code. For example [22.38stable vs 22.39](https://github.com/yuliskov/SmartTube/compare/22.38s...22.39). Same is for 22.38vs22.39.
There are no differences in code, so I wonder what makes 22.39 work? I guess there is something on the build pipeline, but then again you have insutrction on how to build which are not depended on the build pipeline.

Thank you

**Comment by WolfganP** [comment]
There were tons of changes in the submodules 22.39 (https://github.com/yuliskov/SmartTube/commit/2f3bfee911b5f6898471e7021d4e9913b49a4476), so maybe 22.39 only includes changes in there rather than the UI main code.

**Comment by Anonymous941** [comment]
@WolfganP The commit you linked to was for 22.37...

**Comment by Anonymous941** [comment]
@WolfganP It would have to bump the version number at least...

**Comment by Sarafian** [comment]
I didn't check the history and the timestamps. My mistake comparing versions that both had the same history. Apologies and closing.
