### ISSUE TITLE
403 Error is showing it's ugly again

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#3674]
I've tried to play videos on 22.41 and the error 403 showed up again, I uninstalled version 22.41 downgraded to 22.39, Same thing. YT is really pushing this.

**Comment by ACR-Jeff** [comment]
I have noticed if waiting about a minute it will still play some videos

**Comment by waneco-git** [comment]
22.39 Was pefectly fine for me yesterday and even a few hours ago yet just now got the 443 error, updated to 22.41 and error persisted. Its back :(

**Comment by ShamelessWizard** [comment]
I had videos failing. I just forced a resign in with the long press option. Now things are playing. Makes sense if it’s a 403.

**Comment by CodeCubeNeo** [comment]
Its part of a bigger problem, google changed api calls again and all 3rd party yt apps have 403s... https://github.com/TeamNewPipe/NewPipe/discussions/11260. Also has the main developer ever considered to use an outside yt extractor, so problems like that are handled upstream? something like https://github.com/TeamNewPipe/NewPipeExtractor

**Comment by ShamelessWizard** [comment]
The YT downloader libs are attractive because there is a lot of community support. It's probably a good idea to distance from them with YT's aggressive posture on the public APIs. The re-signin seems to be working enough for me this evening. I do agree with you, but not my code base!

**Comment by ACR-Jeff** [comment]
Today now non live steam videos aren't playing at all. It brings up the player, Yet clicking play does nothing. I've tried to force shut down the app and play again, I've tried to reboot my device, Same thing.

**Comment by ACR-Jeff** [comment]
Few hours later and everything started working again on it's own, Except still getting a 403 error message, Waiting a minute and the videos play.

**Comment by TheColdOne** [comment]
Was on 22.39 until I started seeing 403 a while ago and updated to 22.41.

I am also seeing the video not playing initially (403 Unknown), but then after 30+ seconds it will start up.

**Comment by ShamelessWizard** [comment]
I updated to the latest, forced a re-sign in and I haven't had an issue all day. Live streaming and static videos are fine.

**Comment by Lanset2000** [comment]
@ShamelessWizard  Can you watch resolutions higher then 1080p?

**Comment by ShamelessWizard** [comment]
Nope, I’ve tried while logged in and logged out. I briefly had some 4k play the other day, but I can’t reproduce it. I fiddled with presets too.

**Comment by Lanset2000** [comment]
Same with me, only 1080p :(

**Comment by ACR-Jeff** [comment]
My issue has been resolved by the latest beta version 22.43

**Comment by ShamelessWizard** [comment]
The real resolution was the friends we made along the way.
