### ISSUE TITLE
Only AVC Codec after "403 Error" fixes

### ISSUE THREAD

**Issue by clrizzi** [yuliskov/SmartTube#3704]
After the fix for **403 Error** I'm getting only **AVC** Codecs in all videos. I can't switch to **VP9** or **AV1** on video resolutions.

Anybody else with this same problem?

**Comment by mrfhenix** [comment]
Same here Android 9 google tv was working with the previous beta

**Comment by jkwcurtis** [comment]
Same here on the Onn TV

**Comment by edgan** [comment]
The latest 22.43 beta release, from two hours ago, works both for vp9 and 4k for me. I also haven't seen any 403 errors.

**Comment by clrizzi** [comment]
Yes, the VP9 and AV1 codecs are working again. Sometimes I still get some 403 error messages but then the video opens.

**Comment by clrizzi** [comment]
Fixed after last updates!

**Comment by kockok** [comment]
my device is xiaomi "A pro" MITVOS, I can see 4K videos even with the latest version.
After some research, I dig that my device has no vp9 codec preinstalled. What could I do to watch 4K videos? Thanks.
