### ISSUE TITLE
5.1 Audio options now missing under Audio formats in version 22.38

### ISSUE THREAD

**Issue by Raul824** [yuliskov/SmartTube#3719]
Smarttube app was able to show 5.1 streams on some videos which had eac3 5.1 codecs. Even the official app doesn't support that but only smarttube was showing those options and suddenly it disappeared.

I have tried with same videos but the option isn't appearing.

5.1 videos can be found at multiple youtube channels.
Below is one such example which I use for testing.

5.1 surround mixes by Methuselah's Grandpa

**Comment by andrzej-gmt** [comment]
I have noticed the same problem, 5.1 tracks are still accessible with FreeTube on PC.

**Comment by andrzej-gmt** [comment]
Corrected in version 22.44. Thanks!
