### ISSUE TITLE
New update not working.

### ISSUE THREAD

**Issue by Patraputt** [yuliskov/SmartTube#3720]
![17213222304206538557296404322224](https://github.com/user-attachments/assets/3be52e20-aa43-4ea0-a15d-d0cda2e15243)
Currently on 22.44, but the update isn't working as intended. Videos and Audios are not playing, showing "Disabled". VP9 has returned when Live streaming. Please rectify it. 🙏🏻

Tested on: FireTv stick Max

**Comment by rodalpho** [comment]
You may want to go into video formats and presets menus and ensure nothing is set to “disabled”. I believe he made a change where disabled means video itself is disabled, IE you don’t get any.

**Comment by Thayblood** [comment]
After this update, there are some videos that don't load the image or the audio but the bar keeps running smoothly showing that the video is as if it were normal, you know when you're watching it but the majority of it isn't catching, does anyone know why?

**Comment by rodalpho** [comment]
That’s how it works when I disable video or audio yes, whatever I didn’t disable continues to play. This feels weird as it’s a change (I think) but could be useful if you want to just play audio from a music video or something. Don’t know why you’d do the reverse versus just muting but I guess it’s consistent.

**Comment by Patraputt** [comment]
> You may want to go into video formats and presets menus and ensure nothing is set to “disabled”. I believe he made a change where disabled means video itself is disabled, IE you don’t get any.

There is nothing else rather than "Disabled" options showing in the "Video formats" and "Audio formats".

**Comment by ErvinMark** [comment]
Same for me I have to go back few times and after it's opening , but really slow !

**Comment by Thayblood** [comment]
I also noticed an error in this update that the 1080/60/AVC resolution is lagging every video I upload, the videos that sometimes load as I warned yesterday in that post and it's not my device

**Comment by Patraputt** [comment]
The update isn't working at all.

**Comment by fail-0verflow** [comment]
Updated to 22.44 last night on my GoogleTV, it worked fine for like 20 hours and now again getting error code 403.

**Comment by Patraputt** [comment]
> Updated to 22.44 last night on my GoogleTV, it worked fine for like 20 hours and now again getting error code 403.

I also have Google TV and the update doesn't work on GTV as well.

**Comment by Pantalaim0n** [comment]
22.48, problem still remains

No 403 error but videos "playing" with both no video and no audio

**Comment by Patraputt** [comment]
Updated to 22.49, everything was working fine for just 3 minutes and then ghost playback started again! Videos "playing" with no video and no audio!

**Comment by Patraputt** [comment]
Updated to 22.51, Ghost playback is still persistent. Videos "playing" with no video and no audio!

**Comment by Patraputt** [comment]
Updated to 22.55, Ghost playback is still persistent. Videos "playing" with no video and no audio!

**Comment by Patraputt** [comment]
https://github.com/user-attachments/assets/0818572e-001d-4415-805d-6dcdc8a3978b

"Ghost playback"

**Comment by Patraputt** [comment]
Updated to 22.56, Ghost playback is still persistent. Videos "playing" with no video and no audio!

**Comment by Patraputt** [comment]
Everyone, please update to 22.65. It'll work like a charm!

**Comment by Patraputt** [comment]
Everyone, please update to 22.65. It'll work like a charm!
