### ISSUE TITLE
Beta 22.59 Update broke everything

### ISSUE THREAD

**Issue by BabaYaga34** [yuliskov/SmartTube#3740]
Everything was working great before the 22.59 update and now nothing plays anymore on an Nvidia Shield TV.

Edit: Only live streams still seem to be working, but not other videos.

**Comment by Patraputt** [comment]
Updated to 22.59, Ghost playback is still persistent. Videos "playing" with no video and no audio!

**Comment by ihauh** [comment]
403 error for me.

**Comment by Geruda32** [comment]
Same here, 22.59 update broke video playback, like no internet connection.

**Comment by Netsky60** [comment]
I got 2 versions on my Shield :

22.59 Beta version
22.38 stable version
I used the Beta version this morning (was 22.44), no issue, and this evening 403 errors started to appear. I upgraded the beta version to 22.59, same issues.
Tried Stable version, all is working fine on Nvidia Shied 👍

I always keep a working version and i upgrade the other one to last version.

**Comment by Totoro1975** [comment]
Same here. Google TV. Latest update broke. Prevoius  version was flawless

**Comment by qoaa** [comment]
Everything was working fine, got an update notification and decided to go ahead while I was busy doing something else. Came back to open a video and noticed nothing plays now. I see the thumbnails and such  but when I go to play any video I get an error 403 now.

**Comment by Annathin** [comment]
I was working until I did the beta 22.59 update a few minutes ago. Now stuck in the Response Code: 403 endless loop.

**Comment by happyguy1** [comment]
i run both beta and stable on an sony android TV - as others reported, 22.59 broke beta - even before it broke, other beta updates still initially displayed the 403 error code, but then after a couple seconds, resolved and played the video - after 22.59, the 403 error code persists and won't play anything - ST stable plays fine, though seems it might not be in as high of resolution? - as always, GREAT thanks to Yuriy for his amazing efforts in protecting our minds from melting down with commercials!!

**Comment by hay** [comment]
Using 22.60 on Chromecast TV, had the same dreaded 403 error. Cleared the cache and app files (so basically re-installing) seems to have fixed it. Lost all the settings but at least it works again.

**Comment by ihauh** [comment]
After a few tries, v. 22.60 can play videos though limited to 1080 resolution.

**Comment by Nano0k** [comment]
Yeah, same story for me on a Fire Stick. After a few weeks of playing "leap frog," with getting the 403 error, and you fixing it, and back and forth, the *last* update (22.57?) was working smoothly for me for about a week. I just saw the 22.59 update and, even though it didn't have your "don't update if your version is working," warning, I updated without thinking, "maybe wait to see how this one works for others" and here we are.

Tried different Player>Video presets resolutions/frame rates/codec settings, which may have helped with one update a few weeks ago, all to no avail.

Getting the 403 error again. :/

Thanks for all your hard work!

-N

P.S. Has anyone tried to revert back to 22.57b, or even the last stable version? If it has worked, care to share your method, or point to a guide?

**Comment by Annathin** [comment]
Did the update 22.61. Not getting the 403 error. But, the video still won't play, and still no time/video duration showing. Using Amazon Fire TV Cube and I did a restart 3x.

**Comment by Mudflapper** [comment]
All the beta versions from today result in no playback. The regular release 22.44 is playing everything while occasionally cycling through your various 403 fixes, however it's back to limited formats; AVC 1080 max. This is on a Tivo Stream 4K. (Thanks for doing what you do!)

**Comment by Annathin** [comment]
Did the update 22.63. Not getting the 403 error. New message,  undefined:23: SyntaxError: Unexpected token ';' .Using Amazon Fire TV Cube.

Thanks for working so hard to fix the problems!

**Comment by Nano0k** [comment]
22.64 works for me on Fire Stick, thanks! I got an "unrecognized token" error for a few seconds of black screen, then vid started! I also changed my Player>Video presets to "no preset" before I updated from 22.63>.64. Not sure if that helped, but I'm not touching anything now that it's working again.

Thanks again!

**Comment by Annathin** [comment]
Did the update 22.64. Not getting the 403 error. Had to restart my fire tv a few times, but the undefined:23: SyntaxError: Unexpected token ';' message is now gone. Videos playing normally again.

Thanks for working so hard to fix the problem!

**Comment by BabaYaga34** [comment]
22.65 works perfect! No more errors or looping before playback. Thank you for all your work and the quick resolution!

**Comment by Mudflapper** [comment]
22.65 brought back VP9, 4K, and HDR. Everything is working perfectly. Thank you so much.
