### ISSUE TITLE
403- Issue started again

### ISSUE THREAD

**Issue by bhanuagarwal73** [yuliskov/SmartTube#3752]
Guys again seeing 403 error

**Comment by toonnongaeoy** [comment]
lgtm.
![image](https://github.com/user-attachments/assets/71154cc2-d30c-46e6-ba70-e8ba9a70fa8c)

**Comment by BruceSRC** [comment]
Update to latest.
I had the same issue and the app wouldnt auto update. Downloaded/installed latest (22.65 beta) and its working again.

**Comment by bhanuagarwal73** [comment]
My bad. It was 22.44
Updated to 22.65 just now.

**Comment by bhanuagarwal73** [comment]
Seems issue with lower version. Updated it...
