### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Mrunknow3** [yuliskov/SmartTube#3766]
Normal video almost every time works fine, but i watch in 1.5x yt after speeding 1-2 minutes that 403 error comes.

**Comment by Patraputt** [comment]
New version? Do you mean 22.70? It seems 22.70 currently fixes the issues.

**Comment by TheTacoNut** [comment]
> New version? Do you mean 22.70? It seems 22.70 currently fixes the issues.

I don't see a new version :(

**Comment by Patraputt** [comment]
> > New version? Do you mean 22.70? It seems 22.70 currently fixes the issues.
> 
> I don't see a new version :(

You have to install beta.

**Comment by Mrunknow3** [comment]
Yes 22.70

**Comment by Shirsegal2** [comment]
בגירסת 70 שוב בעית תרגום לעברית.
איך אני יכול לחזור לגירסת 69

**Comment by Mrunknow3** [comment]
Now working fine I close this isssue

**Comment by Shirsegal2** [comment]
עובד תקין
