### ISSUE TITLE
[BUG]: beta 22.82, Selected SUBTITLE format isn't supported

### ISSUE THREAD

**Issue by BobbyWibowo** [yuliskov/SmartTube#3784]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

beta 22.77

### Device Type

Smart TV/Box

### Affected Android

Android TV 12

### Steps to reproduce the bug

1. Try to watch any video
2. Enable subtitle of any language. Does not matter if standard subtitle or autogenerated subtitle.
3. ...
4. Profit?

### Actual behavior

![Screenshot_20240730-222454](https://github.com/user-attachments/assets/0f7d47be-0a51-4c68-bd22-8ce18b64a79c)

### Additional information

I'm quite certain it happens to all videos on my end, but I'll link some videos I have personally confirmed to be legitimately broken anyway:
https://www.youtube.com/watch?v=q83KKPTh49A
https://www.youtube.com/watch?v=16gB2BDXwTo
https://www.youtube.com/watch?v=Oj0plwm_NMs

**Comment by BobbyWibowo** [comment]
Appears to be fixed in beta 22.79

Many thanks!

**Comment by ren008** [comment]
Issue is back as of 22.81 for me.

**Comment by BobbyWibowo** [comment]
Ah shit, can confirm.. reopened...

**Comment by ren008** [comment]
Rolled back to 22.80 for now and they work. Cant find 22.79.

**Comment by BobbyWibowo** [comment]
Confirmed still broken in 22.82

**Comment by BuzzFuzz** [comment]
Same here..![PXL_20240802_230338022~2.jpg](https://github.com/user-attachments/assets/22f88d08-e8c5-4a91-9784-bfa1d057e098)

**Comment by BobbyWibowo** [comment]
Appears to be fixed as of **beta 22.93**
Thanks!
