### ISSUE TITLE
[BUG]: Black screen/403 error

### ISSUE THREAD

**Issue by purplescorpion1** [yuliskov/SmartTube#3805]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

22.90

### Device Type

Smart TV/Box

### Affected Android

Nvidia Shield Android 11

### Steps to reproduce the bug

Play any video

### Actual behavior

Just get a black screen or sometimes get 403 error with a message saying do not close the player applying fix but still the screen just remains black

### Additional information

Running on Nvidia Sheild

**Comment by purplescorpion1** [comment]
Just updated to 22.90 - same issue

**Comment by purplescorpion1** [comment]
hmm it suddenly started working again. I'll leave it open in case anymore fixes need doing

**Comment by Jmoores812** [comment]
Mine has not been fixed, still a black screen when trying to play the video. The open screen, channels, etc. are all still there, it just won't play. I did clear the cache, forced closed and tried again.

**Comment by ACR-Jeff** [comment]
I just started to get this same issue on Nvidia Shield with 22.93 Beta

**Comment by ACR-Jeff** [comment]
Just loaded Two videos that wouldn't play in 22.93 Beta with 22.81 Stable are working good so far.

**Comment by ACR-Jeff** [comment]
2 videos that wouldn't load in 22.93 Beta I loaded 22.81 Stable and they worked so far. I did notice 22.81 is getting the 403 with a black screen, Yet waiting a minute or so starts the video.

**Comment by ItsCh1ck3n** [comment]
Trying to watch any video black screen nothing but the name of the video, casually clicking pause/play a few times says Unknown 403 error Do not close the player applying the fix 5 minutes later still nothing after leaving it alone when it shown the toast

**Comment by ItsCh1ck3n** [comment]
Some videos do load after the toast but not many

**Comment by ACR-Jeff** [comment]
I've noticed some videos will not play, Until after I force close 22.81 stable and clear it's cache, Load it again, Some videos play.

**Comment by favna** [comment]
Facing the same issue on 22.81 stable on a Sony Bravia TV with Android TV built in.

**Comment by remizik** [comment]
Same issue on a Fire Cube TV gen3 with version 22.81

**Comment by ozernets** [comment]
Same on FireStick 4K, version 22.81.

**Comment by drg0nz0** [comment]
I had the same issue on a fire TV Stick and smarttube 22.81.

 I disabled the Sponsorblock feature and the playback just worked again. Then I enabled sponsorblock again and it keeps working. 😄

**Comment by remizik** [comment]
I managed to make it work by playing a very old video and playing a recent one after. Unless it's a coincidence lol

**Comment by JRPeq** [comment]
Same on Nokia streaming box 8010. I'm on latest version, tried clearing cache and data but no luck. I have also tried to play 5 or 6 different videos, but none played.

**Comment by LulaksDE** [comment]
> I managed to make it work by playing a very old video and playing a recent one after. Unless it's a coincidence lol

Can confirm, on my fireTV stick 4k max, I started playing "me at the zoo" to confirm your steps, and it played. As it was playing I scrolled down to play the recent scrapyard wars episode which didn't load before. Now it did, so thanks! 🙏🏼

**Comment by remizik** [comment]
> > I managed to make it work by playing a very old video and playing a recent one after. Unless it's a coincidence lol
> 
> Can confirm, on my fireTV stick 4k max, I started playing "me at the zoo" to confirm your steps, and it played. As it was playing I scrolled down to play the recent scrapyard wars episode which didn't load before. Now it did, so thanks! 🙏🏼

Make it make sense :D

**Comment by ACR-Jeff** [comment]
Just got an update to 22.94 Beta, It's working so far, Just has a delay at the start of playing a video. But happy it's working again. Thank you

**Comment by purplescorpion1** [comment]
As this seems fixed in the latest beta I am closing the issue
