### ISSUE TITLE
Stuck in infinite update loop

### ISSUE THREAD

**Issue by 44cK3r** [yuliskov/SmartTube#3840]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.12

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

Try to update

### Actual behavior

I'm stuck on Version 23.12 every time I try to update it to 23.13 my TV does install it but it's still says it's on 23.12 hence still saying that there's an update available but I've already installed it Version 23.13 is a broken mess

**Comment by Thayblood** [comment]
In my case, no video loads for me, the screen goes black and there is no sound, the video appears or anything, and after a few moments with this black screen, error 404 appears and the black screen continues.

**Comment by 44cK3r** [comment]
> In my case, no video loads for me, the screen goes black and there is no sound, the video appears or anything, and after a few moments with this black screen, error 404 appears and the black screen continues. 

Were you too lazy to fill out the bug report form?
As that isn't even close to my bug
