### ISSUE TITLE
[BUG]: 23.17 Beta crash after each video

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#3849]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.17 Beta

### Device Type

Smart TV/Box

### Affected Android

Nvidia Shield 8.2.3 Android TV version 9

### Steps to reproduce the bug

Play video with "Stop playback after one video" will cause ST to crash after each video. 

### Actual behavior

Latest update 23.17 Beta Play video with "Stop playback after one video" will cause ST to crash after each video. 
Prior version 23.15 Beta fixed this issue, Now it's back in 23.17 Beta

### Additional information

Nvidia Shield 8.2.3 Android TV version 9

**Comment by Hexinator1302** [comment]
I can confirm, I also have the beta version 23.17 and use the box Ugoos AM8 with android 11.

**Comment by ACR-Jeff** [comment]
I also have 22.95 Stable installed as a backup and it's working without issues.

**Comment by ACR-Jeff** [comment]
Closing this issue since a previous issue of the same is re-opened.
https://github.com/yuliskov/SmartTube/issues/3845
