### ISSUE TITLE
[BUG]: Videos using Video formats HDR do not play

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#3868]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.36 Beta and 23.30 Stable

### Device Type

Smart TV/Box

### Affected Android

Nvidia Shield 8.2.3 Android TV version 9

### Steps to reproduce the bug

Open SmartTube
Try playing a video that's not live
Infinity Black screen

### Actual behavior

I tried to play a video in 23.36 Beta, Yet it only gives me an Infinity Black screen when playing a video that's been Uploaded by a channel. I then tried to play the same video using 23.30 Stable and the same happens as the beta version.
I then tried to open the video control panel and several controls are flickering back and forth
I then opened the "Video Formats" Noticed it's set to 1080p, 30fps, 4.25Mbps, vp9, HDR
I switch the format to one without HDR and it plays. Appears to be an issue with HDR formats?

**Comment by Tailszefox** [comment]
This isn't an issue with STN.

YouTube provides HDR videos in VP9.2 or AV1, neither of which are supported in hardware by the Shield. You could maybe force software decoding, but it would be extremely choppy and I'm not sure it would actually show HDR content correctly.

You'd have the same issue if you used the official app (which would probably not even let you try HDR), or tried downloading and playing the video with Kodi.

If you want to watch HDR content on YouTube you'll have to get a different device that does support one (or both) of the aforementioned codecs.

**Comment by ACR-Jeff** [comment]
> This isn't an issue with STN.
> 
> YouTube provides HDR videos in VP9.2 or AV1, neither of which are supported in hardware by the Shield. You could maybe force software decoding, but it would be extremely choppy and I'm not sure it would actually show HDR content correctly.
> 
> You'd have the same issue if you used the official app (which would probably not even let you try HDR), or tried downloading and playing the video with Kodi.
> 
> If you want to watch HDR content on YouTube you'll have to get a different device that does support one (or both) of the aforementioned codecs.

Thank you for this information, I am new to the shield so I learned something from this, I will be sure to switch the video format and just enjoy. Cheers
