### ISSUE TITLE
Auto Scroll in Subscriptions tab and on YouTubers channels

### ISSUE THREAD

**Issue by 44cK3r** [yuliskov/SmartTube#3877]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.65

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

Just scroll in the Subscriptions tab

### Actual behavior

It keeps on doing an auto infinite scroll until I press the button to make it go in the opposite direction

Edit: it does it on YouTubers channels now as well

**Comment by 44cK3r** [comment]
Update: it seems to be mostly effected on channels

**Comment by Wolf68k** [comment]
Have you checked the batteries in your remote? My Fire TV does this some times when the batteries start to go or when the TV is still in it's "warming" up phase after I've turned it on.

**Comment by 44cK3r** [comment]
> Have you checked the batteries in your remote? My Fire TV does this some times when the batteries start to go or when the TV is still in it's "warming" up phase after I've turned it on.

Ah that explains why I haven't seen it happen since the battery change thank you so very much

**Comment by 44cK3r** [comment]
> Have you checked the batteries in your remote? My Fire TV does this some times when the batteries start to go or when the TV is still in it's "warming" up phase after I've turned it on.

My remote has new batteries and it still happens so it's definitely a bug

**Comment by Wolf68k** [comment]
And it only happens in SmartTube and nothing else?

**Comment by 44cK3r** [comment]
> And it only happens in SmartTube and nothing else?

Yep

And I always wait 5 or so minutes after booting my TV up

**Comment by 44cK3r** [comment]
It just did it again
