### ISSUE TITLE
[BUG]: Chapter markers not showing in seek bar

### ISSUE THREAD

**Issue by Muffin1611** [yuliskov/SmartTube#3915]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.59

### Device Type

Smart TV/Box

### Affected Android

Fire OS 7.6.7.9

### Steps to reproduce the bug

1. Open a video with timestamps
2. Check seek bar

### Actual behavior

No chapter marks show in the seek bar, and no chapter select beneath the video.

### Additional information

This is on a FireTV Stick 4K Max.

**Comment by Muffin1611** [comment]
This isn't always present, and I can't tell what triggers the bug. During normal usage just suddenly chapters disappear on starting a video, when they were showing for other videos before that. Restarting the app didn't solve it, and I had them reappear the day after and disappear again after a couple hours.

**Comment by Muffin1611** [comment]
> I can confirm that this behavior is also reproduced on an Android TV OS 10 version but for me it is consistent and not intermittent. Same videos watched on either official YT app OR on a browser contain chapters.

It has been consistent for me for a couple days now as well.

**Comment by V4ler1an** [comment]
I also completely lost chapters about when you logged this issue. **_I've just discovered that if I log out of my YouTube account hey presto, chapters are working_**. Log back in again, they're gone. So there may be something profile / account related here. Hope it's fixed soon, chapters are so important.

**Comment by V4ler1an** [comment]
Tried two different Google accounts, both the same, no chapters.

**Comment by 0Gentleman** [comment]
Same problem for me.
It's on my both TV with fire stick.

**Comment by onlytanmoy** [comment]
I am facing the same problem in my Shield TV, the chapters beneath the seek bar no longer present.

**Comment by ctnkyaumt** [comment]
same. using android tv (version 9).

**Comment by illuvattarr** [comment]
Same problem for me since a few days on Android TV on a Shield Pro. No chapters in any videos that do have them when played in browser or in the official app.

**Comment by squ1jee** [comment]
Same issue for me on fire cube tv

**Comment by mrnot81** [comment]
Same issue for me on a Firestick 4k Max.

**Comment by Nenes19** [comment]
me too stable version on a Firestick 4k Max but not on béta ? fixed ?

**Comment by gregbythebeach** [comment]
Glad it's not just me. I spent so much time going through the settings trying to figure out what I had turned off or how to turn it back on. The chapters disappeared and weeks ago and I thought it was something I did.

**Comment by Londino** [comment]
For me this is just a deal-breaker that I'm switching to the official YT app whenever i wish to watch a video with chapters.

**Comment by Muffin1611** [comment]
> For me this is just a deal-breaker that I'm switching to the official YT app whenever i wish to watch a video with chapters.

This issue has been fixed with the latest update.

**Comment by LeCommonMan** [comment]
on version 24.37 , the bug seems to present.

**Comment by DasClarky** [comment]
Getting this bug with 31.73 on Shield TV Pro.
