### ISSUE TITLE
[BUG]: Network engine changing randomly

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#3964]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.59 Stable

### Device Type

Smart TV/Box

### Affected Android

Nvidia Shield 8.2.3 Android TV version 9

### Steps to reproduce the bug

Play videos or live streams

### Actual behavior

I can go to Settings > Player > Network engine
Make sure it's set to my desired network engine which is Cronet
Play some videos or live streams and after some time I will noticed poor quality video playback (Seems to happen more often while playing live streams)
Go back to check the Network engine and it at random will be changed to usually Default but I have also caught it changed to OkHttp a few times. 
This makes video playback on my device very noticeable in terms of poor quality with lots of buffering compared to Cronet.

### Additional information

Nvidia Shield 16gb 8.2.3 Android TV version 9

**Comment by Marlowe-66** [comment]
I had this happen to me last night. I've been getting a lot of buffering in the last two months, but this is the first time I noticed the network engine setting had changed by itself. I had it set on Cronet and it changed itself to OkHttp, which is very slow on my setup.

**Comment by Marlowe-66** [comment]
I've been keeping an eye on the network engine setting over the last couple of days and it seems to change by itself quite a bit. I'm checking it when I get a lot of buffering and it's often (but not always) changed from where I set it.

Is this a bug or an unwanted feature?

**Comment by ACR-Jeff** [comment]
> I've been keeping an eye on the network engine setting over the last couple of days and it seems to change by itself quite a bit. I'm checking it when I get a lot of buffering and it's often (but not always) changed from where I set it.
> 
> Is this a bug or an unwanted feature?

Yes exactly what's been happening on my end, I hope it's a bug that gets fixed because once it changes it doesn't revert back to what setting is wanted by the user. And then you're facing tons of buffering and poor quality video.

**Comment by Marlowe-66** [comment]
I tried a setting last night that was suggested by the dev and it seemed to fix the problem.

Go to Settings > Player > Network engine > Developer Options and enable 'Disable automatic network error fixing'

I also have 'Prefer IPv4 DNS' enabled there.

**Comment by ACR-Jeff** [comment]
Thank you, I will be trying this now!

**Comment by ACR-Jeff** [comment]
Thank you, This seems to have fixed it for me.
