### ISSUE TITLE
[BUG]: emitGroups: BrowseTab of type 0 is null

### ISSUE THREAD

**Issue by NaufalF22** [yuliskov/SmartTube#3986]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.20

### Device Type

Smart TV/Box

### Affected Android

Android tv 9

### Steps to reproduce the bug

just cant load any video tab
![image](https://github.com/user-attachments/assets/b876a41b-bdd8-4613-bf06-9478573d62a7)

**Comment by bumashak** [comment]
Hi, have you been able to solve this problem?

**Comment by 9w2xne** [comment]
It seem problem rely on tv settings. Need to set time to auto update

**Comment by meine12** [comment]
have the samу problem

**Comment by Wetalya** [comment]
у меня аналогичная ошибка.
возникает если запустить vpn через powerTunnel.

**Comment by NaufalF22** [comment]
> Hi, have you been able to solve this problem?

Something along the way about internet connection

**Comment by jhertel** [comment]
This happened to me now, and the reason was that my internet connection was down at the router/ISP level, i.e., there was still a connection to the router, but there was no internet.

I guess a solution could be to actually detect this and tell it, instead of this cryptic message.

**Comment by jhertel** [comment]
I chose to edit the sections (Settings → General → Set-up Sections) by removing the checkmark of some of the sections I don't use anyway (Kids, Sports, Gaming), and now the Home section works again without the "emitGroups: BrowseTab of type 0 is null" error.

So I guess SmartTube got something wrong in the configuration when the internet was down, and that had to be fixed by touching the section setup.

It's quite strange how an internet connection problem can change something in the configuration (without the user touching the configuration), but apparently it did.

**Comment by ricardogarceb** [comment]
Please re-open this is not solved and it has nothing to do with internet connection. I can watch Prime Video  Crunchyrool, whatever but YouTube is not working.
I am using a ChromecastTV 4k

**Comment by Buzzthebuzzsaw** [comment]
This has just popped up as an issue here too.
Looking at Youtube on a browser shows that it thinks the session is offline which it isn't.  Doing a Shift+Reload to force a full reload seems to fix it temporarily and allows a video to play.  Maybe there's something changed on the youtube side that can be corrected for?
Hopefully there's a fix on the way for this?

**Comment by marcoaraujojunior** [comment]
> Please re-open this is not solved and it has nothing to do with internet connection. I can watch Prime Video Crunchyrool, whatever but YouTube is not working. I am using a ChromecastTV 4k

https://github.com/yuliskov/SmartTube/issues/4085
