### ISSUE TITLE
[BUG]: Automatically opens app from background after a few minutes when on other apps

### ISSUE THREAD

**Issue by megamorphg** [yuliskov/SmartTube#4031]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.14

### Device Type

Smart TV/Box

### Affected Android

Android TV 12

### Steps to reproduce the bug

1. Open SmartTube, play a video, play in background, re-open, pause video, and then exit app completely.
2. Open a different app and play a video or even go home

### Actual behavior

After a 2 minutes, the SmartTube app automatically opens even if a different video is playing on the different app.
This occurs regardless of whether SmartTube was explicitly exited or the video was paused.

### Additional information

Using Onn Streaming Device 4k Pro

**Comment by cschritt** [comment]
This might be related to the issue described in #3170
