### ISSUE TITLE
[BUG]: This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions.

### ISSUE THREAD

**Issue by jbfirefox** [yuliskov/SmartTube#4040]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.37

### Device Type

Smart TV/Box

### Affected Android

12

### Steps to reproduce the bug

1. Log in to your YouTube account in Smarttube.
2. Play any video from your history, which otherwise does not appear in Smarttube channels or subscriptions.

### Actual behavior

Many (restricted?) videos don't appear in the Smarttube-App. When playing a restricted video from the history this error message is shown:

"This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions."

YouTube content restrictions settings:
https://www.youtube.com/check_content_restrictions

Restrictions on your organization's network
DNS restrictions are disabled
HTTP header restrictions are disabled

Restrictions for your personal account
Restricted Mode: Disabled

### Additional information

I already tried to log out and in.
I tried to reinstall both the 24.37 beta and stable versions.

**Comment by jbfirefox** [comment]
I already tried to log out and in.
I tried to reinstall both the 24.37 beta and stable versions.

**Comment by edgan** [comment]
The URL for a video as an example would be useful.

Your country might be useful information.

Are you sure this isn't an example of videos you watched that were later restricted, and the error message is to be expected?

**Comment by jbfirefox** [comment]
Example for restricted video: https://youtu.be/miJv8MKl870

About the YouTube "Restricted Mode":
https://support.google.com/youtube/answer/174084?hl=en

Location is Germany. 

Video plays fine on the official YouTube app or in Chromium based browsers. The error only occurs occasionally with the SmartTube app.

![PXL_20241026_161059537~2](https://github.com/user-attachments/assets/fa69d56b-e800-4716-a2d8-6c6f15e6f149)

**Comment by edgan** [comment]
I just tried you video, and it works for me.

1. Played in a browser logged into my US based Google Workspace YouTube account
2. Went one of my Nvidia Shields and updated SmartTube to 24.38
3. I was already logged in with the same YouTube account, and went to my history
4. Selected the video as the first video in my history, and it played just fine

Note, one way of probably side stepping this issue is not to use a Google Workspace based account, but a normal Gmail account. Various Google services have weird restrictions on them if you use a Google Workspace based account. The big one that comes to mind is Google Home(the speaker devices).

**Comment by edgan** [comment]
I put your error message into Google. I found these links you might find interesting.

https://old.reddit.com/r/k12sysadmin/comments/10rwtrr/problems_with_youtube/
https://old.reddit.com/r/youtube/comments/kq02ev/unable_to_turn_off_youtube_restricted_mode_even/
https://old.reddit.com/r/k12sysadmin/comments/l6cnj5/cant_approve_any_youtube_videos/

You most likely problem is related to the DNS servers you are using. They might be some odd default DNS servers from your Android device, or coming from your network ISP. I would try setting them manually to some combination of the ones below and see if it helps.

8.8.8.8
8.8.4.4
1.1.1.1

It really could be Google Workspace settings, but that seems unlikely given you say it works in the normal YouTube app, and elsewhere.

You might try the video while not logged in, and see what SmartTube does. Also you might try resetting SmartTube's settings, and then re-logging in, it might help.

**Comment by edgan** [comment]
I just installed 24.38 on my Android 15 based smartphone. I had some trouble getting my account logged in. Once I was logged in I went to my history, and again I was able to play your example video.

You could try doing the same on your phone, if it is Android.

**Comment by jbfirefox** [comment]
Thank you very much for your help. I don't have a Google Workspace Account. I just found a solution by activating an deactivating the restricted mode for my YouTube account in the settings on my PC. Now everything works fine again.

![blog-youtube-restricted-mode-en-1](https://github.com/user-attachments/assets/b96cba04-4798-4e67-bd54-820af42fd0c8)

**Comment by nFo911** [comment]
Just wanted to say thanks 

And confirm that the safe search also affects youtube 

Youtube restricted mode settings are accessible only after the safe search is disabled in ad guard. 

Now videos are no longer “restricted” 

<img width="1170" height="2532" alt="Image" src="https://github.com/user-attachments/assets/9d7f70a6-12f1-4357-923b-ee761fcb0fe6" />
