### ISSUE TITLE
[BUG]: Can't see Subscriptions, Trending or open playlists and channels

### ISSUE THREAD

**Issue by Kosert** [yuliskov/SmartTube#4054]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.37 stable, 24.50 beta

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

When going to Subscriptions:
- blank screen or "Can't load content" screen is shown

When going to Trending:
- error is shown: "emitGroups2: groups are null or empty"

When going to Playlists:
- playlists show correctly, but when trying to open them nothing happens

When going to any channel:
- no content is shown, only searchbar at the top
- I can't actually search the channel, blank screen is shown in place of results

Other sections seem to work correctly, history for my account is shown, I can add videos to playlist when watching, but can't actually see playlists.
I tried removing all data and logging in again with no effect. Also tried installing newest beta, but the same happens there.

### Additional information

Device is Philips TV

**Comment by dlrhas21** [comment]
Same issue on nVidia Shield.  Was on the first version that came out after the 403 error... updated to the latest stable and beta versions with same results.

**Comment by gohlhausen** [comment]
Same on ONN 4K, ONN 4K Pro, Odroid N2 w/ Android TV.

I have a large number of subscriptions (400+), if that makes a difference.  Some of these channels are likely removed, banned or otherwise problematic.

**Comment by TVlurker** [comment]
same issue on firestick android  TV- not logged in but all saved channels say emiGroups2: groups are null or empty on a black screen. On the history I can actually see the thumbnails of what I watched, but they do not play. The history is the only place i can see anything. Have the latest version. Happening since yesterday evening

**Comment by JobDestroyer** [comment]
I believe I am also running into this bug, but I have a few additional annoyances. 

 - I cannot log in on the first try. It simply "doesn't take", but after several attempts it works for a little bit
 
  - When this happens, the app works fine
  
  - Eventually I'll restart the device and I'll be incapable of seeing subscriptions or channels or searching at all. The app acts as though it is totally offline, I can't even check for updates. 
  
  Nvidia Shield with LineageOS +MicroG. Reimaged the shield and the issue persists on a clean install. Happens in both beta and stable branches.

**Comment by gohlhausen** [comment]
The account I am having problems with is a channel created when google forced brand accounts on users several years ago.  It has "google-" in the email associated with that account.   I deleted this account and added my subscriptions to my mail google account.
When I switched to my regular google account, I didn't have any problems.  I needed to sign out of the problem account before all errors went away, though. (I was getting the "emitGroups: BrowseTab of type 0 is null" error loading the home tab).

**Comment by 44cK3r** [comment]
I had no such problem until the 24.51 update that said it fixed it now I have to wait for another update to actually fix it

**Comment by Kosert** [comment]
On 24.51 I can see most of the issues fixed, although I still cannot open some playlists. I think it's a problem with private playlists, as public and unlisted ones open just fine. This is bit annoying as Watch Later can't be changed from Private.

**Comment by Salamat-UK** [comment]
> Same in FireTV (on TCL Fire TV)

Also same on Redmi Note 12. Did try relogging in, but no difference.

**Comment by Kosert** [comment]
I can see there is a separate issue about opening private playlists (https://github.com/yuliskov/SmartTube/issues/4057), since the rest seem to be fixed, I'm closing this issue.

**Comment by inMikeRotch** [comment]
Is there an ETA when this fix will be available on stable? Thank you.
