### ISSUE TITLE
[BUG]: "Can't display content" after deleting subscription groups.

### ISSUE THREAD

**Issue by github-monkey** [yuliskov/SmartTube#4094]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.62

### Device Type

Smart TV/Box

### Affected Android

Shield Android TV 11

### Steps to reproduce the bug

1. From your Playlists section, pin a playlist to the sidebar.
2. In Subscriptions, find a video from the channel the playlist you pinned is from. Use the context menu to add the channel to a subscription group.
3. From the sidebar, delete all subscription groups using their context menus.
4. In the sidebar, check if the previously pinned playlist still works.
5. If not, remove the playlist from the sidebar, then go to Playlists and pin the same playlist to the sidebar again.
6. In the sidebar, check if the playlist works. 
7. If not, then go to the channel the playlist is from, and from there pin the playlist again to the sidebar.
8. In the sidebar, check if the playlist you pinned from Playlists works, and check the one you pinned directly from the channel.

### Actual behavior

After adding several channels to a couple of subscription groups and then deleting them, without removing their linked channels first, all playlists that were pinned to the sidebar from inside the Playlist section start showing "Can't display content."

Removing them from the sidebar and re-adding them from Playlists gives the same result. Only by going to the channel that any of the affected playlists are from, and then pinning them from there, will they show their items again from the sidebar. Even if removing and re-adding the playlist from Playlists first.

### Additional information

Nvidia Shield pro. Nothing noteworthy happened besides me experimenting with subscription groups, and then deleting them without first removing the channels that were part of the subscription group. Then about a day later I started noticing this.

I TRIED: 
Restarting the device. 
Force stopping and starting the app.
Signing out and in.
Deleting the cache. 
Deleting the data.

**Comment by github-monkey** [comment]
Solved by update 24.71.

**Comment by 43Rageon** [comment]
A subscription group cannot be removed after it is pinned to the side. When I long-press the button, it shows the options "Refresh section", "Move section up", "Move section down" but there is no option to delete the section. How can I delete it?
