### ISSUE TITLE
Videos don't play at all anymore they don't even try

### ISSUE THREAD

**Issue by 44cK3r** [yuliskov/SmartTube#4130]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.71

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

Try and play any video

### Actual behavior

Now all I get is this it doesn't even try anymore: 
![IMG20241121134930](https://github.com/user-attachments/assets/8676dd90-585a-4044-8d68-145450809f04) I've been waiting for 5 minutes now and no change but everything else works fine

**Comment by Cronogargaros** [comment]
me too, with last versions (since some months)

**Comment by laughtLOOL** [comment]
same here but it has a message show，(unknown source error response code：403 don‘t close the player，applying the fix..... end) if not login doesnt play any，if try playing button muti times the videos title will change to (please login)
then if login then can play one videos then the login status was drop need to be login use code again fff

**Comment by theicevalkyrie** [comment]
Installed on firestick - Samsung tv. Same app version, same playback error where it hangs and while I see account info/subscriptions the notifications refresh shows errorresponse: request contains an invalid argument. Sign in. 

Restarted app and firestick. Signed back in. Then found this reported issue.

**Comment by cynister76** [comment]
Same on my Firestick.  Nothing plays, since this morning :(

**Comment by leffu33** [comment]
Same problem here. Mibox4. The error with info about applaying fix stop popsup but "buffer loop" still occures.

Also i get notification that new version is avaiable(24.74) but i cannot istall it.
Try 3 times. Everything looks like update is installed but when i open app there is still 24.71 version with notification about update.
