### ISSUE TITLE
[BUG]: Selected AUDIO format isn't supported

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#4138]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.76 Beta

### Device Type

Smart TV/Box

### Affected Android

Nvidia Shield 8.2.3 Android TV version 9

### Steps to reproduce the bug

Open SmartTube
Play any video

### Actual behavior

Video won't play, Error shown with a popup "Selected AUDIO format isn't supported."

### Additional information

Tried the same videos in 24.71 Stable and they play fine.

**Comment by edgan** [comment]
Try updating to 24.77 beta. It works for me on my Nvidia Shield. Though 24.76 beta also worked for me.

Also in general, a lot the time historically if you get the `audio not supported` error rebooting helps.

**Comment by ACR-Jeff** [comment]
> Try updating to 24.77 beta. It works for me on my Nvidia Shield. Though 24.76 beta also worked for me.
> 
> Also in general, a lot the time historically if you get the `audio not supported` error rebooting helps.

Yes I just finished updating, Works great.
Prior I did clear all my apps cache and restarted multiple times without solving the issue.
But update 24.77 Beta solved it. Thanks
