### ISSUE TITLE
[BUG]: Home menu not loading, blank screen with spinning circle 

### ISSUE THREAD

**Issue by qoaa** [yuliskov/SmartTube#4140]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.78

### Device Type

Smart TV/Box

### Affected Android

Amazon Fire TV Cube (2nd Gen) 

### Steps to reproduce the bug

Open the SmartTube app, then select Home

### Actual behavior

Before the recent 2 patches that mentioned fixes for Home issues the only way I could get any videos to show up in Home was to log out. While logged in everything else worked like subscriptions, news, trending, searches all worked but home was blank. Then after a recent patch when I went to Home it displayed the message "Browsetab of type 0 is null" on screen.

Now after the most recent patch it no longer gives an error message, it just stays blank while a loading circle icon spins seemingly forever. All the other sections like subscriptions, news, etc all still work fine, just for some reason Home isn't loading.

### Additional information

I tried testing by logging into another account and it's the same where all the sections work except the Home section doesn't load and just does the spinning circle icon.

**Comment by KingBarker** [comment]
This happens to me also. I have to go under settings, open the account menu, then go to playback and change the network to default back to cronet. Then I can see videos in my feeds and maybe play one before having to do it again

**Comment by qoaa** [comment]
I'm closing this since the last 2 patches fixed the problem and the Home section finally loads again and haven't had any trouble with Home since patching.
