### ISSUE TITLE
[Feature Request]: How can I use the original language without translation

### ISSUE THREAD

**Issue by Oimel1981** [yuliskov/SmartTube#4153]
### Describe the feature you'd like to request

Videos use not the original language. They are translated. I want to use the original language without change the language every time I watch a video.

### Describe the solution you'd like

A option to use only the original language without translation.

### Describe alternatives you've considered

A option to use only the original language without translation.

**Comment by einsern** [comment]
A setting to to ignore those horrible autotranslations would be great. Or at least sort the original version to the very top or something?

**Comment by etaxi341** [comment]
Please add this... This new YouTube translation feature is such trash

**Comment by fargiolas** [comment]
if is there some workaround or hidden option to disable this please expose it in smart tube!

**Comment by ktp1976** [comment]
Original language as general option or remember the settings per channel would be nice. The robotic KI translation voice sucks. Maybe usefull for languages I don't understand, but those I understand, I'd really like to stay original.

**Comment by paulb-102** [comment]
It is possible to change the audio track behavior in SmartTubeNext (i hope it is the same for SmartTube) for each video and also as default.
**Default behavior** can be set under:
under Settings > Player > Audio Language
If you want the original audio stream of the video select 'none', else select the your language of choice (might be AI dubbed). If you have selected something else than 'none' and this language is not available in a specific video the player will default to the original audio language.
**Per Video selection**
start a video; under quality settings (the 'HQ' symbol lower left) select 'Audio formats'. There you can select different audio streams.

I hope you all can enjoy the original audio again. The AI was so bad, my dad even thought his fire tv stick had a virus while he tried watching an English speaking house building video...

Thanks to the makers of ST / STN!!!

**Comment by fargiolas** [comment]
> It is possible to change the audio track behavior in SmartTubeNext (i hope it is the same for SmartTube) for each video and also as default. **Default behavior** can be set under: under Settings > Player > Audio Language If you want the original audio stream of the video select 'none', else select the your language of choice (might be AI dubbed). If you have selected something else than 'none' and this language is not available in a specific video the player will default to the original audio language. **Per Video selection** start a video; under quality settings (the 'HQ' symbol lower left) select 'Audio formats'. There you can select different audio streams.

Thank you! but I still get the super annoying AI voice-over even if I have "None" both globally and per-video. Also tried changing the UI language as that affects translation of video titles (which was already pretty annoying)... no effect.

**Comment by paulb-102** [comment]
I'm using SmartTube beta 25.09 on an Amazon fire TV stick

In my last post i made a small mistake:
In the video; under quality settings (the 'HQ' symbol lower left) select 'Audio language' (not 'audio formats'). There you can select different audio streams.

I have set language German, Country Germany in the 'Language/Country' settings. This does translate the titles into German. If i set it to English, Country US i get English titles.

some more testing...
If i set the Settings > Player > Audio Language to 'none' i get the original video language and in the video under the HQ > audio language (not audio-format, sorry my mistake) i can change the language as expected between German and English and others.
If i set the Settings > Player > Audio Language to 'Deutsch' i get the AI dubbed German version and in the video under the HQ > audio language i can change the language as expected between German and English
If i set the Settings > Player > Audio Language to 'English' i get the English version and in the video under the HQ > audio language i can change the language as expected between German and English.

So it behaves as i would expect.

I was using the following video for testing:
https://www.youtube.com/watch?v=E1bZtHV8Lo0

Hope this helps!

**Comment by spunkt123** [comment]
> some more testing... If i set the Settings > Player > Audio Language to 'none' i get the original video language and in the video under the HQ > audio language (not audio-format, sorry my mistake) i can change the language as expected between German and English and others. If i set the Settings > Player > Audio Language to 'Deutsch' i get the AI dubbed German version and in the video under the HQ > audio language i can change the language as expected between German and English If i set the Settings > Player > Audio Language to 'English' i get the English version and in the video under the HQ > audio language i can change the language as expected between German and English.

When i change Audio Language to 'none' the videos are translated to french. But my region settings are Germany and the videos are from the USA. 🤔

**Comment by paulb-102** [comment]
hard to tell what the prolem is as it might depend on the remaining setting.
What happens if you change language/country in the main settings to English/US and the audio language in the main settings also to english, do you get english audio?
Are you able to change the language in a video (via HQ>audio language)?

**Comment by Oimel1981** [comment]
> hard to tell what the prolem is as it might depend on the remaining setting. What happens if you change language/country in the main settings to English/US and the audio language in the main settings also to english, do you get english audio? Are you able to change the language in a video (via HQ>audio language)?

Then everything will be translated to English even if it's not the original language of the Video. I can change the language in the Audio Settings but I have to do it every time I watch a video with another language than the last video I watched.

**Comment by Oimel1981** [comment]
With Player -> Audio Language -> None ist seems to work at the Moment.
