### ISSUE TITLE
[BUG]: Can't sort channel list by new content

### ISSUE THREAD

**Issue by gcogger** [yuliskov/SmartTube#4166]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.90

### Device Type

Smart TV/Box

### Affected Android

Android TV 12

### Steps to reproduce the bug

Go to Settings, User Interface, Channels section sorting
Now only 2 options: Last Viewed and Alphabetically
The option to put channels with new content at the top has disappeared. 

### Actual behavior

Need the ability to have channels with new content at the top of the list.
Ideally the other channels would then follow alphabetically, as they used to, but that was already broken in the last few versions. 

### Additional information

Chromecast with Google TV

**Comment by dontwantonebutneedone** [comment]
Same thing. Its only got "alphabetical" and "last viewed" while it formerly had four options including new content. Still broken with the update that just came in the past hour or so.

**Comment by gcogger** [comment]
Sort by new content is back in 24.92, thanks
