### ISSUE TITLE
[BUG]: Touchscreen device lost ability to select tiles, goes into play on a single tap

### ISSUE THREAD

**Issue by seppuko** [yuliskov/SmartTube#4184]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.97 Beta

### Device Type

Smartphone

### Affected Android

Android 12

### Steps to reproduce the bug

1. Enter home screen.
2. Tap once any tile on the right.

### Actual behavior

From application enter if a user wants to select a tile to scroll the list on the right they would normally tap a tile once, that would select the tile and they would be able to scroll further. As of 24.97 tapping once immediately starts the video. This prevents from scrolling and selecting.

**Comment by Wolfeman28** [comment]
Same issue on all of my touchscreen devices. While the old way was somewhat 'klunky', at least it was predictable. Since the last update, it's borderline unusable.

**Comment by WolfganP** [comment]
Same here. Maybe this [fix](https://github.com/yuliskov/SmartTube/commit/66d719d49c8a52a02c69c44042e6ed9c712b7342) working outside the intended context of the player?

**Comment by seppuko** [comment]
Fixed in 25.04 Beta

**Comment by Wolfeman28** [comment]
Can confirm 👍
