### ISSUE TITLE
[BUG]: No video playback on FireTV- v25.03

### ISSUE THREAD

**Issue by carry-mulligan-1992** [yuliskov/SmartTube#4186]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

25.03

### Device Type

Smart TV/Box

### Affected Android

Fire TV

### Steps to reproduce the bug

Issue:  nothing will play with 25.03 on FireTV
1- Logout of app
2- Clear Data and clear cache
3- Restart FireTV

### Actual behavior

Neither logout nor Clear Data and Clear Cache  resolved the issue. Only the spinning status wheel is displayed.

**Comment by darkza** [comment]
same, somehow magically works again
