### ISSUE TITLE
[BUG]: beta 25.04, yet another video constant buffering issue?

### ISSUE THREAD

**Issue by BobbyWibowo** [yuliskov/SmartTube#4189]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

beta 25.04

### Device Type

Smart TV/Box

### Affected Android

Android TV 12

### Steps to reproduce the bug

1. Play any video
2. It'll constantly buffer every few seconds, seemingly always unable to fill enough buffer for an uninterruptible experience

### Additional information

I'm on a Chromecast with Google TV (HD)

Also, I was able to play a bunch of videos for hours on end throughout the whole day with no issue, **until just about 30 mins ago.**

Sample video with confirmed constant buffer issue, https://youtu.be/u8gnN5UMhEo

Can also confirm it's not my internet, since I can play & buffer the same video just fine on my PC that is connected to the same home Wi-Fi.

**Comment by BobbyWibowo** [comment]
Actually, this might only be specific to certain videos.

I can confirm I consistently get the buffer issue with this video (same link in the original post), https://youtu.be/u8gnN5UMhEo, but I'm not really getting the issue on other random videos..

**Comment by leffu33** [comment]
I picked randomly from my subscriptions videos and non of them work.
As you describe constant buffering.

Mibox4, smart tubę 25.04 beta, android sdk 28

**Comment by brewskybeer** [comment]
Same happening to me.  Constant buffering when trying to play videos

**Comment by Bearbque** [comment]
I'm having the same issue on Google TV. When I click on any video, I get a black buffering window. I left a video open like that, and it's been buffering for maybe 5 minutes now. The video doesn't load.

**Comment by Nemesis2727** [comment]
Yep same for me I can see the videos but nothing will play it just buffers.

**Comment by Belvior** [comment]
I have the same issue it's like 2 weeks now 🥲

**Comment by outrunpro** [comment]
Also seeing the same issue; spinning donut on a black background when trying to play videos.  Tried a variety of videos with no luck.

Same issue on NVidia Shield and Fire TV Cube.

**Comment by nikospamp** [comment]
Same behavior on mix box 3, latest fw.

**Comment by techbot2342** [comment]
Can't play anything

**Comment by clementmoine** [comment]
After some minutes there is a 403 snackbar message that says a patch is being activated but keeps buffering after that

**Comment by Ghostwithoutashell** [comment]
Issue just cropped up for me NVIDIA Shield Pro  with latest stable build installed.

**Comment by leffu33** [comment]
After cleaning data and logged in once again  video start working.

**Comment by Bearbque** [comment]
Clearing data did NOT work for me, unfortunately

**Comment by mattm3** [comment]
Issue happening for me on Nvidia Shield as well. Thought it was my internet lol

**Comment by astraetech** [comment]
2nd gen firestick 4k max with both updated main and beta STN. No videos load at all on both branches.

**Comment by oynsy1** [comment]
Same for me, nvidia Sheild and Sony google tv, nothing plays, force stop, clear cache/data, reinstall both beta and stable release eventually get 403 error and then applying fix which doesn't work

**Comment by DiscoFever78** [comment]
+1  Same here on v24.89... Just curious: Is the alphabetical channel sorting at least fixed finally in beta v25.04, anyone?

**Comment by awesomebytes** [comment]
Same here, Google TV, stable, nothing loads, infinite buffering donut

**Comment by rindertb** [comment]
+1 Google TV, 24.89

**Comment by bobnecat** [comment]
Adding too the list.  

Looks like YT is at it again.

**Comment by uniolix** [comment]
Same. Was working after initial install of 25.04 last night, next morning all I see is buffering circle. Device is a Fire TV Cube(2nd gen).

**Comment by Error1404** [comment]
Same issue for me with Fire stick 25.04. Videos will not play, just the spinning symbol.

**Comment by RicME85** [comment]
So I am experiencing the buffering circle when trying to play anything on an Nvidia Shield and a Chromecast with GoogleTV in the bedroom yet in the lounge there are two Firesticks that are working fine. Very odd. Firesticks - one has stable one has beta. Shield stable, CCwGT is on beta.

**Comment by outrunpro** [comment]
> After cleaning data and logged in once again video start working.

Didn't work for me sadly but worth a go.

**Comment by BobbyWibowo** [comment]
I think all is well now, especially with beta 25.14 that allegedly improves performance further. Tyvm for the hard work!
