### ISSUE TITLE
[BUG]: Smarttube not loading video

### ISSUE THREAD

**Issue by JSB1940** [yuliskov/SmartTube#4191]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.89

### Device Type

Smart TV/Box

### Affected Android

Fire TV

### Steps to reproduce the bug

Loaded app
It didn’t play the videos
Closed it
Force stopped it
Cleared cache
Rebooted the fire to
Still wouldn’t work

### Actual behavior

Hiya
None of the videos will play
Really weird
PS I wasn’t aware you had patreon so I’ll be donating today
Love the app!

### Additional information

Fire TV

**Comment by ACR-Jeff** [comment]
Same issue here on Nvidia Shield, I've tried clearing cache, data, restarting and re-logging in but not working. Tried a vpn and didn't solve it, Just shows a black screen with the spinning wheel.

**Comment by Jahfry** [comment]
Confirmed. Sony A80K.

**Comment by MatzeX71** [comment]
Same here on Xiaomi with Google TV.

**Comment by appleprayduty** [comment]
Having Same issue on Nvidia Shield. just started happening an hour ago.

**Comment by sartanafc** [comment]
> Same here on Xiaomi with Google TV.

+1

**Comment by dmmagit** [comment]
Same issue here, Chromecast with Google TV

**Comment by DaveHaymes** [comment]
Same issue, Amazon Fire TV.

**Comment by linasma** [comment]
Confirmed on Xiaomi Mi stick 4k and Google Chromecast with Google TV.

**Comment by selam** [comment]
same issue, also i try uninstall and install again, aft downloader cant access to download link, 
i reinstall older version from disk, problem remains.

**Comment by burggraf** [comment]
Same -- Amazon Firestick 4K Max.

**Comment by mirko77** [comment]
Same on Sony TV.

**Comment by Howking007** [comment]
Just like us. Sony TV, Android 10. Until I try to play something, the video thumbnails load. As soon as I try to play something. Thumbnails that I haven't loaded yet won't load again until I exit and launch the app. At first I thought it was some sort of YouTube countermeasure against the app, but this behavior is may be indicative of an app bug (or an app bug caused by a YouTube countermeasure).

**Comment by lauriliiv** [comment]
Same on xiaomi mi stick 4k and xiaomi mi tv. Tried stable 24.89 and beta 25.04

**Comment by fitzperfect** [comment]
Same here with ONN4KPro

**Comment by adriandiazgar** [comment]
Same here in a TCL android 8

**Comment by johnroberts2k** [comment]
same issue with mine on Amazon fire stick and fire TV and google chrome TV. it was working then an update popup came and after updating it stopped loading any videos. Tried loading old version using APK I had but still same problem

**Comment by InsecurePassword** [comment]
Same issue here on my pixel.  Started an hour or two ago.  Was working on my fire stick this morning.

**Comment by sasa-fajkovic** [comment]
Same here on nVidia Shield Pro. App is on the latest version (25.04)

**Comment by hypo-thesis** [comment]
Doesn't work on any of the networks either, default or cronet ( is it ? )

**Comment by Mudflapper** [comment]
Same here on TiVo Stream 4K. Was working this morning.

**Comment by TauLieR64** [comment]
Same here, android Box TV from Internet Service Provider.

version 24.89

Clear cache done.
Login again
Still not working

**Comment by mariusgrams** [comment]
Same here, tested with latest version on fire tv

**Comment by Fat-Zilla** [comment]
Same for Firestick 4k Max, including "Live" content, nothing loads.

**Comment by forceoflife69** [comment]
I thought it was my internet until I checked. Internet works but Smarttube currently not playing any vidoes.

Tried all the fixes other people tried but still Smarttube not playing videos.

Can you please provide fix? 

Thank you for your help

**Comment by Kodikodiko** [comment]
Sony tv here, release and beta version not working

**Comment by grf1951** [comment]
Same here on Firestick 4k Max. However occurred after Firestick update. Notifications not working for a couple of months now.

**Comment by Masterlocker** [comment]
Same on xiaomi mi tv stick

**Comment by EvansJD2112** [comment]
Same issue in UK on 2x Shield Pro.
Was working this morning
24.89

**Comment by Alamo04** [comment]
Same Here, with FireTV 4K Max Stick.

**Comment by SJB-NL** [comment]
Same on my Nvidia shield pro.
Installed the beta, same problem, now back on stable, reboot a few times.
Still no luck...

But on my phone and tablet its still working fine. 😵‍💫

**Comment by Windwisperer** [comment]
Same issues as noted above on a firestixk 4k max. Worked several hours ago for me.

**Comment by cushycrux** [comment]
It's funny how google is investing millions and million to abuse us to watch their god dammned AI slop and right wing ads. It's almost funny.

**Comment by Frenkone** [comment]
Italy, Sony Android TV: same issue.

**Comment by lukolszewski** [comment]
Yes, broken here on Sony Bravia too.

**Comment by VnkCCENcXH0c3AhnijQ0y7SBeZx27** [comment]
Youtube killed a Rust tool that is essential to watch videos on Invidious (inv_sig_helper). looks like Smart Tube uses the same stuff (?)

**Comment by IsoNovio** [comment]
Same

**Comment by grf1951** [comment]
Was just about to install beta version. I won't now. Hope this is sorted
soon.

**Comment by STARevolution** [comment]
Screwtube is a money hungry, censorship happy service. I wish Google had never bought it. I hope Google is sued into bankruptcy for censorship. Hopefully, someone can come up with a better service and I am not sure why no one has yet. And they are mad because Tiktok is taking a lot of revenue from them, So they are adding more and longer ads to make up for this. Regular Youtube is unwatchable now.

**Comment by oddlife** [comment]
Videos not loading for me either. Using Chromecast with Google TV

**Comment by lucasmz-dev** [comment]
Reproduceable on a TCL Android TV (not that... it isn't everywhere at this point 🥲)

**Comment by mirko77** [comment]
@VnkCCENcXH0c3AhnijQ0y7SBeZx27 
> interestingly, ymusic.io is not affected

NewPipe is still working fine as well.

**Comment by Wolf68k** [comment]
I'm glad to know it's not just me with my run of bad luck int the last 24 hours.

On a Fire Edition Fire TV. 
 Tested with both Stable 24.89 and Beta 25.04. Force quit and cleared the cache on both.

**Comment by clarkejaal** [comment]
Same here on Amazon Fire Stick 4K. Have two of these devices and Smart Tube has been temperamental over the past two weeks.

LOVE the app, hope this is able to get resolved soon. 🙏

**Comment by ebrummer** [comment]
same on NVidia Shield with 25.04 beta.

**Comment by bubuleur** [comment]
same problem here nvidia Shield TV Pro

**Comment by ckrause7** [comment]
Same here, nvidia Shield.

**Comment by ModischFabrications** [comment]
I think we can all stop posting comments with "same", I'm pretty sure there is enough evidence of it happening on many different platforms. Let's keep it down and let them fix it, I'm sure they will ask for more details if they need them.

**Comment by bubuleur** [comment]
> I think we can all stop posting comments with "same", I'm pretty sure there is enough evidence of it happening on many different platforms. Let's keep it down and let them fix it, I'm sure they will ask for more details if they need them.

Yes you are right we need to give time for the dev to fix it

**Comment by JSB1940** [comment]
> I think we can all stop posting comments with "same", I'm pretty sure there is enough evidence of it happening on many different platforms. Let's keep it down and let them fix it, I'm sure they will ask for more details if they need them.

Think it’s important to have the information on which platforms this is occurring 
Also release numbers and locations

**Comment by cspencer49519** [comment]
I'm running a cheap onn 4k streaming box, I am obviously experiencing the same issue. I also tried the official YouTube app on the same box, it will not even load the interface, just sits at the YouTube logo with a spinning circle. Is this some sort of device level ban?

**Comment by noobshoes** [comment]
Same here on a firestick

**Comment by metalfoxdev** [comment]
Can confirm this on a UK firestick. Worked on my Sony Android TV this morning.

**Comment by LinuxUnix80** [comment]
Same here on 4k Amazon Fire Stick.

**Comment by jackL999** [comment]
This issue is not exactly the same as the one posted a few days ago. 

https://github.com/yuliskov/SmartTube/issues/4181

**Comment by Ayyan83** [comment]
Same issue here with google tv started this evening

**Comment by shoguevara** [comment]
Same issue on a Shield TV. Youtube Premium subscriber.

**Comment by Zak321** [comment]
24.61 Stable is working for me on a Fire Stick.  It took a bit of time for the first video to start but later videos start fine.  25.04 Beta is not working on the same device.

**Comment by FabioM3** [comment]
A quick reminder for people to **DONATE**, now you see how this app is needed.

**Comment by fuzunspm** [comment]
Same issue on chromecast

**Comment by Subtixx** [comment]
Maybe related to: https://github.com/iv-org/inv_sig_helper/issues/36#issuecomment-2529123709

**Comment by kkrusher741** [comment]
Confirming issue on firestick. Any updates?? Please advise.

**Comment by QuietlyCreative** [comment]
Not working for me on Nvidia Shield.
Have 2 identical devices, both running both stable and beta, same versions of both. Beta on my bedroom device stopped working first. Stable stopped working an hour or two later. Living room device continued working for less than an hour after that.

My guess is that YT are detecting the use of Smart Tube and blocking the sessions or something similar.

**Comment by grf1951** [comment]
No updates yet.

**Comment by Ausschaltknopf** [comment]
SmartTube_stable_24.61_armeabi-v7a
works fine at my Device
Formuler Z11 Pro Max 4k Bt1

**Comment by ninjakitty7** [comment]
Happening on my fire stick, no apparent fix. Updated app, cleared cache, force stop, restart device. Videos never load, time shows as -- / -- 

It seems like the videos failing to play/load at all happens in conjunction with the home page failing to populate. Infinite loading wheel appears when trying to scroll left or right. Also can’t scroll down through video recommendations during playback anymore, the categories no longer appear. These three issues all started happening at the same time, though videos aren’t working at all today where they would eventually work before.

Is a specific network engine recommended? I don’t know what to do with the setting since it was introduced.

**Comment by cynister76** [comment]
Same on Amazon Firestick.  Cleared cache and data, won't play videos.  I love Smarttube so much, hope it works, soon.

**Comment by AppieDappie** [comment]
Same here, Nvidia Shielt TV Pro
Can load thumbnnails, channel data and even previews within Android TV, but doesn't play video, only black screen and loading spinner.

**Comment by rainman74** [comment]
Workaround here: https://github.com/yuliskov/SmartTube/issues/4194

**Comment by tcpaulh** [comment]
=========

24.61 works 

=========

**Comment by rainman74** [comment]
Note: 24.61 also works, but the loading times are somewhat slower than with 24.53 and the first video start also takes much longer. Therefore I personally recommend 24.53 until @yuliskov offers a fix. This will certainly not take too long ;-)

**Comment by Cbramblejr** [comment]
> Note: 24.61 also works, but the loading times are somewhat slower than with 24.53 and the first video start also takes much longer. Therefore I personally recommend 24.53 until @yuliskov offers a fix. This will certainly not take too long ;-)

Where can I get 24.53 all I seem to find is the latest stable release

**Comment by rainman74** [comment]
> > Note: 24.61 also works, but the loading times are somewhat slower than with 24.53 and the first video start also takes much longer. Therefore I personally recommend 24.53 until @yuliskov offers a fix. This will certainly not take too long ;-)
> 
> Where can I get 24.53 all I seem to find is the latest stable release

Workaround here: https://github.com/yuliskov/SmartTube/issues/4194

**Comment by ACR-Jeff** [comment]
An update was just pushed out 25.08 fixes it for me

**Comment by Kodikodiko** [comment]
Fixed within a few hours. This dev definitely earns some support!!

**Comment by mateutaque** [comment]
Yes issue fixed on Google Chromecast. You are crazy guys all of my respect for this time to solve problem ! Less than 8h to restart the service you have all of my respect !

**Comment by rololo88** [comment]
Well done guys ! Works so far here on android TV and chinese laser prjector

**Comment by JSB1940** [comment]
Hiya 

> ### Checklist
> * [x]  I made sure that there are _no existing issues_ - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> * [x]  I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
> * [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
> * [x]  This issue contains only one bug.
> 
> ### Affected version
> 24.89
> 
> ### Device Type
> Smart TV/Box
> 
> ### Affected Android
> Fire TV
> 
> ### Steps to reproduce the bug
> Loaded app It didn’t play the videos Closed it Force stopped it Cleared cache Rebooted the fire to Still wouldn’t work
> 
> ### Actual behavior
> Hiya None of the videos will play Really weird PS I wasn’t aware you had patreon so I’ll be donating today Love the app!
> 
> ### Additional information
> Fire TV

Hi Sweets!
It’s working here today!
Thank you ever so much for this!
Heading over to donate!
Happy Holidays!
J (c:

**Comment by grf1951** [comment]
Fixed for me. Just notifications now to free up. The original problem. Well
done devs.

**Comment by bertonumber1** [comment]
Also facing this same issue and its really as if the fixes in the last few updates have just broken something else. I cast from youtube revanced on my phone as i cant remember the last time i could view a video on ST. 

Device Nvidia Shield Pro 2019
Non Rooted Android 11

**Comment by mirko77** [comment]
Thanks devs! 

All good!

**Comment by linajululian** [comment]
Kindly note since the last update, facing endless difficulty with most of the videos whether long or short, old or new, keeps stating don't close it is getting fixed!! It doesn't fix any, it starts to play for seconds then stops and so on!!

Fyi same videos played smoothly on YouTube!!

**Comment by rainman74** [comment]
> Kindly note since the last update, facing endless difficulty with most of the videos whether long or short, old or new, keeps stating don't close it is getting fixed!! It doesn't fix any, it starts to play for seconds then stops and so on!!
> 
> Fyi same videos played smoothly on YouTube!!

I cannot confirm this. All videos run flawlessly with the latest version, even on 5 different TV sets.

**Comment by EvansJD2112** [comment]
> Kindly note since the last update, facing endless difficulty with most of the videos whether long or short, old or new, keeps stating don't close it is getting fixed!! It doesn't fix any, it starts to play for seconds then stops and so on!!
> 
> Fyi same videos played smoothly on YouTube!!

No issues since last update for me.
2x nVidia Shields, Google Chromecast and Sylvox TV all fine.

What device are you using?

**Comment by linajululian** [comment]
It used to work perfectly prior last update.. using G Guard TV OS version 11

**Comment by linajululian** [comment]
Meant android OS version 11

**Comment by linajululian** [comment]
![17344518126273679601127010387771](https://github.com/user-attachments/assets/4f6972dd-cfc7-48dd-9d0b-e58c5a31fa95)

**Comment by linajululian** [comment]
Already have it..

**Comment by linajululian** [comment]
Now most of history videos not available!!

**Comment by linajululian** [comment]
Now all history back.. surely there is something wrong from the main provider

**Comment by linajululian** [comment]
I uninstalled & reinstalled.. problem solved

**Comment by Cbramblejr** [comment]
Can we get the notifications to work again with the next update?

**Comment by grf1951** [comment]
That would be great.

**Comment by johnroberts2k** [comment]
Same with me. Amazon fire stick was working fine then stopped working. Updated to 25.81 which is the latest and now getting response code 403. And it keeps saying applying a fix but doesn’t work.

**Comment by grf1951** [comment]
There's now been an update to Smarttube. It works except for notifications

**Comment by Cbramblejr** [comment]
You have to go to each individual channel that you want notifications to
show up. Then go to the subscribe button, long press and then select "All"
