### ISSUE TITLE
[SOLUTION]: Workaround for latest streaming problem!

### ISSUE THREAD

**Issue by rainman74** [yuliskov/SmartTube#4194]
### Affected version

SmartTube 24.89

### Device Type

Smart TV/Box

### Affected Android

All Android TVs

### Solution
Use the newest version SmartTube 25.08:
https://github.com/yuliskov/SmartTube/releases/tag/25.08s

### Workaround (deprecated)

Today's streaming bug affects all recent SmartTube versions.

To fix this follow these steps:
1. Backup SmartTube settings with Backup/Restore menu (use Google Drive)
2. Uninstall the current version and install the older version 24.53 (link below)
3. Log in with your account via http://youtube.com/activate
4. Restore SmartTube settings with Backup/Restore menu (use Google Drive)
5. Start any video, a 403 error appears, but the stream starts after some waiting time (approx. 10 seconds)
6. A fix is automatically applied, let the video continue to run until the toast message fades out
7. From now on, all videos start normally again, but the loading time are felt to be slightly longer at 2-3 seconds.

SmartTube 24.53:
https://github.com/yuliskov/SmartTube/releases/tag/24.53s

**Comment by Wolf68k** [comment]
In the thread where people are talking about 24.89 not work but 24.61 is working and you're saying 24.53 does as well. But it makes me wonder what else between 24.89 and 24.61 works

**Comment by rainman74** [comment]
> In the thread where people are talking about 24.89 not work but 24.61 is working and you're saying 24.53 does as well. But it makes me wonder what else between 24.89 and 24.61 works

24.61 also works, but the loading times are somewhat slower than with 24.53 and the first start also takes much longer. Therefore I personally recommend 24.53 until @yuliskov offers a fix. This will certainly not take too long ;-)

**Comment by Wolf68k** [comment]
Ok fair enough.

You might want to add to those instructions to backup the settings before uninstalling, so they can restore after rolling back

**Comment by zopieux** [comment]
Confirmed working, thanks for sharing.

**Comment by rainman74** [comment]
> Ok fair enough.
> 
> You might want to add to those instructions to backup the settings before uninstalling, so they can restore after rolling back

Good idea, I've added that to the post.

**Comment by wendzin** [comment]
The method works, but I found that when restoring the settings backup, the problem occurs again, at least here on my device!!!

**Comment by cynister76** [comment]
How can this used for Amazon Firestick?

**Comment by sizzlik** [comment]
> How can this be done for Amazon Firestick?

Same way you installed it the first time. Use the downloader and feed it the direkt link to the apk. After download the stick asks if to install.

Problem i got now..i cant sign in. It says loading code with the QR code..but no code comes =(

**Comment by rainman74** [comment]
> The method works, but I found that when restoring the settings backup, the problem occurs again, at least here on my device!!!

It doesn't matter, step 5 is repeated once more.

But I have adapted the guide, thanks for the tip!

**Comment by cynister76** [comment]
> > How can this be done for Amazon Firestick?
> 
> Same way you installed it the first time. Use the downloader and feed it the direkt link to the apk. After download the stick asks if to install.
> 
> Problem i got now..i cant sign in. It says loading code with the QR code..but no code comes =(

Thank you, there are five options and clueless what to click on.

**Comment by sizzlik** [comment]
> > > How can this be done for Amazon Firestick?
> > 
> > 
> > Same way you installed it the first time. Use the downloader and feed it the direkt link to the apk. After download the stick asks if to install.
> > Problem i got now..i cant sign in. It says loading code with the QR code..but no code comes =(
> 
> Thank you, there are five options and clueless what to click on.

if your stick is a bit older use the armeabi version..dunno if the newest firesticks got 64bit arm processors or still 32

**Comment by rainman74** [comment]
> > > How can this be done for Amazon Firestick?
> > 
> > 
> > Same way you installed it the first time. Use the downloader and feed it the direkt link to the apk. After download the stick asks if to install.
> > Problem i got now..i cant sign in. It says loading code with the QR code..but no code comes =(
> 
> Thank you, there are five options and clueless what to click on.

https://letmegooglethat.com/?q=How+to+install+and+use+Downloader+App+on+Fire+TV

**Comment by EdmundGerber** [comment]
25.08 has been released to address these problems. Can confirm it works!

**Comment by morallys** [comment]
It didn't work for me. The app doesn't install on the suggested versions, whether stable or beta. I'm on a Mi Stick 4k.

**Comment by McCarthee** [comment]
> The method works, but I found that when restoring the settings backup, the problem occurs again, at least here on my device!!!

Make sure you're on the default network engine under settings > player > network engine

I had the same issue, I was messing around with the network engines menu before trying this guide out.

**Comment by McCarthee** [comment]
But 25.08 works for me too.

**Comment by rainman74** [comment]
Use the newest version SmartTube 25.08:
https://github.com/yuliskov/SmartTube/releases/tag/25.08s
