### ISSUE TITLE
[BUG]: Restricted videos no longer play when going through ad blocking DNS

### ISSUE THREAD

**Issue by forgedreality** [yuliskov/SmartTube#4204]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

25.08 and beta 25.09

### Device Type

Smart TV/Box

### Affected Android

Google Chromecast

### Steps to reproduce the bug

Set your network WAN to utilize ad blocking DNS such as AdGard

Play any age restricted video

### Actual behavior

SmartTube displays a restricted error and will not play the video

Prior to the issue from a couple of days ago, where no videos were playing, I did not have to disable my AdBlock DNS. I feel the two issues are related and are countermeasures deployed by Google.

**Comment by Truman78es** [comment]
I'm having the exact same problem. On my Pixel it works perfectly, but on my Chromecast I can't even see videos on channels that have age restrictions. I get a message that says: "This video is restricted. Check with your Google Workspace administrator or network administrator." I'm my own network administrator and I've never used Google Workspace. I can watch it on Youtube using the same user without any problems.
I feel like throwing away the Chromecast and building a multimedia center with a Raspberry and LineageOS...

**Comment by forgedreality** [comment]
UPDATE: !Not an issue!

This is related to the AdGuard DNS servers. I had been making changes to my internet config around the time SmartTube stopped playing videos. I also noticed I was no longer able to comment on some videos from my phone when connected to the wifi.

In my router config, the two DNS servers were not correct. The first one was. The second was one of AdGuard's "family-friendly" servers. Literally one number different than it should have been. If you are experiencing this issue, please check AdGuard's server list and ensure you're using unrestricted DNS servers.

Once I fixed the one that was wrong, and restarted my Chromecast, the problem stopped occurring.

For those interested, the servers I am using are as follows:
94.140.14.14
And
94.140.15.15

That second one had been changed by me at some point to 14.15. There are some other bug reports here that I believe would benefit from this information.
