### ISSUE TITLE
[Feature Request]: Adjust Loudness of Voice Search Beep Sound

### ISSUE THREAD

**Issue by andrewjgoss1** [yuliskov/SmartTube#4218]
### Describe the feature you'd like to request

The beep sound that plays both when initiating and finishing the voice search is quite loud on TVs, so it would be nice to be able to adjust the beep's loudness.

### Describe the solution you'd like

Options to adjust the volume (0%, 25%, 50%, 100%) of the voice search beep sound through the app’s settings.

### Describe alternatives you've considered

No other alternative solution.

Thank you!

**Comment by ACR-Jeff** [comment]
If I am correct the voice search audio would be controlled by your devices system sounds, Maybe adjust it through your device or disabling system sounds?
