### ISSUE TITLE
App has stopped loading any content.

### ISSUE THREAD

**Issue by monstermuffin** [yuliskov/SmartTube#738]
Version 11.47 

Suddenly SmartTuebNext is no longer loading any content. I will get a spinning loading indicator indefinitely. This happened suddenly without an update.  The issue is not being unable to load videos, the homescreen and any tabs themselves do not load any content. 

I have tried removing all data, reinstalling, bypassing pihole restrictions and nothing has seemed to work. 

I did get it to load one time on a fresh install, but it would not load the code for account pairing. After restarting the app, the pairing code showed and my account was paired and I was unable to load anything again. 

Attached is a logcat of starting the app and waiting at the spinning loading indicator.
[smartyoutubenext_logcat.txt](https://github.com/yuliskov/SmartTubeNext/files/6764367/smartyoutubenext_logcat.txt)

**Comment by s-p-a-r-k-y** [comment]
Can confirm that the latest version of the App has stopped loading any content.
Pairs with my account fine, but no content playback.

**Comment by HernanSteel** [comment]
Same probleme here guys.
The app don't load any content.
Device: Xiaomi Mibox S

**Comment by linuxstv** [comment]
![Screenshot_20210710-044528](https://user-images.githubusercontent.com/15664372/125138938-c508b600-e139-11eb-84fd-6844bdfd8942.png)
Mine is still ok.

**Comment by HernanSteel** [comment]
![16258703291557986061555514750140](https://user-images.githubusercontent.com/87209620/125142149-6ae20380-e0ed-11eb-85e6-e9bd7bd46700.jpg)
